import type { RouteCandidateDraft } from './agent-route-planner.ts';
import { browserCockpitLike, browserControlLike, researchRunnerLike, visualResearchReportLike, channelDeliveriesLike, channelSendLike, channelSetupLike, channelTargetFromText, channelTriageLike, externalChannelLike, externalMemoryProviderLike, hasAny, mediaGenerationLike, quote, releaseAuditLike, releaseEvidenceLike, securityFindingLike, securityPermissionLike, securityPolicyExplainLike, securityPolicyToolTarget, securityStatusLike, sessionMutationLike, sessionWorkspaceLike, supportBundleEffectLike, supportBundleLike, ttsProviderLike, voiceWorkflowLike } from './agent-route-planner-helpers.ts';

export function addSurfaceSecurityRouteCandidates(
  lower: string,
  request: string,
  add: (candidate: RouteCandidateDraft) => void,
): void {
if (browserControlLike(lower)) {
    add({
      id: 'browser-control-workflow-plan',
      label: 'Browser, screenshot, or desktop-control workflow plan',
      score: 97,
      userSurface: 'Work & Approvals workspace',
      userOutcome: 'Choose the safest browser, screenshot, or desktop-control workflow before any live UI action.',
      why: 'The request asks for screenshot, browser navigation/control, screen observation, or desktop control.',
      modelRoute: `computer action:"plan" query:${quote(request)} includeParameters:true`,
      inspectRoute: 'computer action:"control" includeParameters:true',
      userRoute: 'Agent Workspace -> Work & Approvals',
      requiresConfirmation: hasAny(lower, ['open', 'control', 'click', 'fill', 'type', 'capture', 'screenshot', 'record', 'desktop']),
      missingFields: ['target page/app/screen when applicable', 'exact live action to perform', 'confirmation for any live-control effect'],
      supportingRoutes: [
        'computer action:"plan" query:"take a screenshot" includeParameters:true',
        'computer action:"mcp" query:"browser desktop" includeParameters:true',
        'computer action:"setup"',
        'computer action:"open_browser" confirm:true explicitUserRequest:"..."',
      ],
      policy: 'Workflow planning is read-only. Browser opens, screenshots, authenticated browsing, form entry, desktop actions, and MCP/tool invocations require the selected tool-specific confirmation boundary.',
    });
  }

  if (mediaGenerationLike(lower)) {
    add({
      id: 'media-generation-artifact',
      label: 'Confirmed media artifact generation',
      score: 94,
      userSurface: 'Voice & Media workspace',
      userOutcome: 'Generate image or video only as a confirmed saved artifact with provider readiness visible first.',
      why: 'The request asks to generate, create, render, or draw image/video/media output.',
      modelRoute: 'device action:"provider" target:"media" includeParameters:true',
      inspectRoute: 'agent_harness mode:"media_posture" includeParameters:true',
      userRoute: 'Agent Workspace -> Voice & Media',
      requiresConfirmation: true,
      missingFields: ['media prompt', 'provider/model if the default is not acceptable', 'confirmation'],
      supportingRoutes: [
        `agent_media_generate prompt:${quote(request)} confirm:true explicitUserRequest:${quote(request)}`,
        'agent_artifacts mode:"list" query:"generated media"',
        'agent_knowledge_ingest sourceKind:"artifact" artifactId:"..." confirm:true explicitUserRequest:"..."',
      ],
      policy: 'Media generation requires an explicit user request and confirmation. Generated bytes are saved as artifacts, not printed inline or silently ingested into Knowledge.',
    });
  }

  if (voiceWorkflowLike(lower) && !ttsProviderLike(lower)) {
    const voiceEffect = hasAny(lower, ['record', 'transcribe', 'start ', 'set up', 'setup', 'enable', 'speak', 'capture', 'open ']);
    add({
      id: 'voice-workflow-posture',
      label: 'Voice interaction workflow posture',
      score: 93,
      userSurface: 'Voice & Media workspace',
      userOutcome: 'Inspect push-to-talk, transcription, spoken-response, and wake-word posture before any voice capture or playback effect.',
      why: 'The request mentions voice workflows, voice memo transcription, push-to-talk, spoken responses, or wake-word capture.',
      modelRoute: `device action:"voice" query:${quote(request)} includeParameters:true`,
      inspectRoute: 'device action:"voice" includeParameters:true',
      userRoute: 'Agent Workspace -> Voice & Media -> Voice readiness',
      requiresConfirmation: voiceEffect,
      missingFields: voiceEffect
        ? ['voice workflow id or audio source', 'selected provider when needed', 'confirmation before capture, transcription, playback, or visible picker handoff']
        : undefined,
      supportingRoutes: [
        'device action:"provider" target:"voice" includeParameters:true',
        'device action:"open_tts_provider" confirm:true explicitUserRequest:"..."',
        'device action:"open_tts_voice" providerId:"..." confirm:true explicitUserRequest:"..."',
        'setup action:"item" setupItemId:"voice-workflows"',
      ],
      policy: 'Voice workflow inspection is read-only. Voice capture, transcription, spoken output, provider picker opens, and wake-word behavior stay unavailable or confirmed until published contracts prove readiness.',
    });
  }

  if (ttsProviderLike(lower)) {
    const openPicker = hasAny(lower, ['open', 'picker', 'choose', 'select', 'change', 'set ']);
    add({
      id: 'tts-provider-posture',
      label: 'TTS provider and voice setup posture',
      score: 92,
      userSurface: 'Voice & Media workspace',
      userOutcome: 'Inspect TTS provider and voice readiness before opening a picker or changing spoken-response settings.',
      why: 'The request mentions TTS, text-to-speech, speech synthesis, voice provider, or TTS voice selection.',
      modelRoute: 'device action:"provider" target:"tts" includeParameters:true',
      inspectRoute: 'device action:"voice" includeParameters:true',
      userRoute: 'Agent Workspace -> Voice & Media -> TTS provider',
      requiresConfirmation: openPicker,
      missingFields: openPicker ? ['provider or voice target when known', 'confirmation before visible picker handoff or setting change'] : undefined,
      supportingRoutes: [
        'device action:"open_tts_provider" confirm:true explicitUserRequest:"..."',
        'device action:"open_tts_voice" providerId:"..." confirm:true explicitUserRequest:"..."',
        'settings action:"list" query:"tts voice" includeParameters:true',
      ],
      policy: 'TTS inspection is read-only. Opening provider/voice pickers or changing spoken-response settings requires explicit confirmation.',
    });
  }

  if (browserCockpitLike(lower)) {
    const openCockpit = hasAny(lower, ['open', 'launch', 'show']);
    add({
      id: 'browser-cockpit-readiness',
      label: 'Connected browser cockpit/PWA readiness',
      score: 93,
      userSurface: 'Connected browser cockpit',
      userOutcome: 'Inspect the configured browser/PWA cockpit and setup routes before opening an external browser.',
      why: 'The request mentions the browser cockpit, PWA, web dashboard, or browser dashboard.',
      modelRoute: 'computer action:"browser" includeParameters:true',
      inspectRoute: 'workspace action:"surface" surfaceId:"connected-browser-cockpit" includeParameters:true',
      userRoute: 'Connected Browser Cockpit (opened through confirmed computer action:"open_browser")',
      requiresConfirmation: openCockpit,
      missingFields: openCockpit ? ['confirmation before opening the external browser/PWA handoff'] : undefined,
      supportingRoutes: [
        'computer action:"open_browser" confirm:true explicitUserRequest:"..."',
        'workspace action:"open" surfaceId:"connected-browser-cockpit" confirm:true explicitUserRequest:"..."',
        'host action:"services" query:"web" includeParameters:true',
      ],
      policy: 'Browser/PWA readiness is read-only. Opening the connected browser cockpit is a visible confirmed handoff; browser-native Agent workspace routes count as ready only from certified SDK/daemon browser/PWA route and first-run receipt read models.',
    });
  }

  // Driving a browser is its own route. Before the browser tool existed, these
  // requests were sent to readiness planners that describe browser control
  // without performing any, which is how a request to open a page turned into
  // a hunt for a tool that could open a page.
  // The GoodVibes browser cockpit, the visual research report, and the
  // browser-backed research runner are their own surfaces with their own
  // routes. They mention browsers without being a request to go drive a web
  // page, so they keep the route they already had.
  // 'screenshot' is deliberately absent: capturing the SCREEN is desktop
  // control. Capturing a page is done from inside a browser session that is
  // already open, so it needs no route of its own.
  const wantsToDriveAPage = hasAny(lower, ['browse', 'browser', 'website', 'web page', 'webpage', 'url', 'navigate', 'click', 'log in', 'login', 'sign in', 'sign-in', 'fill in', 'fill out', 'form', 'scrape', 'on the site', 'web site'])
    && !browserCockpitLike(lower)
    && !visualResearchReportLike(lower)
    && !researchRunnerLike(lower);
  if (wantsToDriveAPage) {
    add({
      id: 'drive-a-browser',
      label: 'Open and act on a web page',
      // Above the browser/desktop workflow planner: when the request is to act
      // on a web page, the answer is the tool that acts on web pages, not a
      // planner that describes how one might.
      score: 98,
      userSurface: 'Browser',
      userOutcome: 'Open the page, read what is on it, and act on it.',
      why: 'The request needs a real web page opened, read, or acted on.',
      modelRoute: 'browser action:"navigate" url:"..."',
      inspectRoute: 'browser action:"status"',
      userRoute: 'The browser window the agent opens',
      requiresConfirmation: hasAny(lower, ['buy', 'purchase', 'order', 'pay', 'send', 'delete', 'cancel', 'submit']),
      supportingRoutes: [
        'browser action:"snapshot"',
        'browser action:"click" ref:"..."',
        'browser action:"type" ref:"..." text:"..."',
        'browser action:"read_text"',
        'browser action:"launch" headless:false profileName:"..."',
      ],
      policy: 'The browser tool drives a real browser directly and provisions one on first use. Every click and keystroke targets an element from a snapshot of a page it controls. Purchases, sends, and destructive actions need explicit user intent.',
    });
  }

  if (hasAny(lower, ['browser', 'pwa', 'dashboard', 'desktop', 'screen', 'screenshot', 'camera', 'voice', 'tts', 'phone', 'mobile', 'device'])) {
    const device = hasAny(lower, ['voice', 'tts', 'phone', 'mobile', 'device', 'camera']);
    add({
      id: device ? 'device-voice-capability' : 'browser-computer-capability',
      label: device ? 'Device and voice capability map' : 'Browser/PWA or computer-use route',
      score: 84,
      userSurface: device ? 'Voice & Media workspace' : 'Connected browser cockpit',
      userOutcome: 'Use device, browser, and desktop capabilities only through visible permission-aware routes.',
      why: 'The request mentions browser/PWA, desktop/computer use, mobile, camera, screen, or voice/TTS.',
      modelRoute: device ? 'device action:"status" includeParameters:true' : 'computer action:"status" includeParameters:true',
      inspectRoute: device ? 'device action:"capability" target:"..." includeParameters:true' : 'computer action:"browser" includeParameters:true',
      userRoute: device ? 'Agent Workspace -> Voice & Media' : 'Connected browser cockpit',
      requiresConfirmation: hasAny(lower, ['open', 'control', 'run', 'speak', 'send', 'capture']),
      supportingRoutes: [
        'computer action:"open_browser" confirm:true explicitUserRequest:"..."',
        'device action:"voice"',
        'device action:"open_tts_provider" confirm:true explicitUserRequest:"..."',
      ],
      policy: 'Capability inspection is read-only; browser opens, TTS picker opens, desktop control, and device effects require visible confirmation.',
    });
  }

  if (externalChannelLike(lower)) {
    const target = channelTargetFromText(lower);
    const setup = channelSetupLike(lower);
    const triage = channelTriageLike(lower);
    const deliveries = channelDeliveriesLike(lower);
    const send = channelSendLike(lower);
    const setupEffect = setup;
    const sendEffect = send && !setup && !triage && !deliveries;
    const channelRoute = target
      ? `channels action:"channel" target:"${target}" includeParameters:true`
      : `channels action:"status" query:${quote(request)} includeParameters:true`;
    const setupRoute = target
      ? `channels action:"setup" target:"${target}" includeParameters:true`
      : 'channels action:"setup" includeParameters:true';
    const modelRoute = deliveries
      ? 'channels action:"deliveries" limit:10 includeParameters:true'
      : triage
        ? 'channels action:"triage" includeParameters:true'
        : setup
          ? setupRoute
          : channelRoute;
    add({
      id: deliveries
        ? 'channel-delivery-receipts'
        : triage
          ? 'channel-triage-route'
          : setup
            ? 'channel-setup-route'
            : send
              ? 'channel-delivery-boundary'
              : 'channel-readiness-route',
      label: deliveries
        ? 'Channel delivery receipts'
        : triage
          ? 'Channel triage and retry posture'
          : setup
            ? 'Channel setup guide'
            : send
              ? 'Confirmed channel delivery boundary'
              : 'Channel readiness',
      score: deliveries || triage || setup || send ? 95 : 88,
      userSurface: 'Channels workspace',
      userOutcome: deliveries
        ? 'Review recent redacted delivery outcomes before retrying or sending more messages.'
        : triage
          ? 'Troubleshoot channel blockers, retries, pending messages, and route bindings without sending.'
          : setup
            ? 'Follow the ordered channel setup guide before relying on external delivery.'
            : 'Send and troubleshoot external messages through configured, inspectable channel targets.',
      why: 'The request mentions external channels, notifications, target setup, or delivery receipts.',
      modelRoute,
      inspectRoute: deliveries ? 'channels action:"status" includeParameters:true' : triage ? 'channels action:"status" includeParameters:true' : 'channels action:"triage" includeParameters:true',
      userRoute: 'Agent Workspace -> Messaging',
      requiresConfirmation: setupEffect || sendEffect,
      missingFields: sendEffect
        ? ['configured target', 'message text', 'confirmation']
        : setupEffect
          ? ['channel/account target', 'configuration or credential route', 'confirmation before mutating channel setup']
          : undefined,
      supportingRoutes: [
        setupRoute,
        'channels action:"triage" includeParameters:true',
        'channels action:"deliveries" limit:10 includeParameters:true',
        'agent_channel_send confirm:true explicitUserRequest:"..."',
        'agent_notify confirm:true explicitUserRequest:"..."',
      ],
      policy: 'Channel inspection is read-only; every external delivery uses an explicit configured target and confirmation.',
    });
  }

  if (hasAny(lower, ['document', 'draft', 'artifact', 'upload', 'export', 'packet', 'handoff', 'blind compare', 'model compare', 'compare models', 'reviewer'])) {
    add({
      id: 'documents-artifacts-compare',
      label: 'Documents, artifacts, and model comparison',
      score: 86,
      userSurface: 'Documents & Files workspace',
      userOutcome: 'Keep drafts, uploads, artifacts, reviewer packets, and model choices in one reviewable workflow.',
      why: 'The request is about documents, artifacts, exports, reviewer packets, or blind model comparison.',
      modelRoute: 'workspace action:"actions" categoryId:"documents" query:"documents compare artifacts"',
      inspectRoute: 'agent_harness mode:"document_ops" includeParameters:true',
      userRoute: 'Agent Workspace -> Documents & Files',
      requiresConfirmation: hasAny(lower, ['create', 'revise', 'export', 'archive', 'share', 'compare', 'apply', 'attach', 'insert']),
      supportingRoutes: [
        'agent_documents action:"browse"',
        'agent_artifacts mode:"list"',
        'agent_model_compare mode:"compare" confirm:true explicitUserRequest:"..."',
        'agent_review_packet_share confirm:true explicitUserRequest:"..."',
      ],
      policy: 'Browsing is read-only; draft changes, exports, archives, sharing, artifact promotion, and comparisons stay confirmed.',
    });
  }

  if (hasAny(lower, ['knowledge', 'ask knowledge', 'search knowledge', 'ingest', 'source node', 'source-backed'])) {
    add({
      id: 'agent-knowledge',
      label: 'Isolated Agent Knowledge',
      score: 82,
      userSurface: 'Knowledge workspace',
      userOutcome: 'Ask, search, inspect, or deliberately ingest reviewed sources into Agent-owned knowledge only.',
      why: 'The request mentions Agent Knowledge, Knowledge search, source-backed answers, or ingest.',
      modelRoute: 'agent_knowledge action:"ask" query:"..."',
      inspectRoute: 'agent_knowledge action:"status"',
      userRoute: 'Agent Workspace -> Knowledge',
      requiresConfirmation: hasAny(lower, ['ingest', 'add', 'promote', 'import']),
      supportingRoutes: [
        'agent_knowledge action:"search" query:"..."',
        'agent_knowledge_ingest sourceKind:"url|file|artifact" confirm:true explicitUserRequest:"..."',
      ],
      policy: 'Agent Knowledge must stay on `/api/goodvibes-agent/knowledge/*` and never fall back to default knowledge.',
    });
  }

  if (securityPermissionLike(lower)) {
    if (securityStatusLike(lower)) {
      add({
        id: 'security-permission-status',
        label: 'Security and permission posture',
        score: 98,
        userSurface: 'Security panel',
        userOutcome: 'Show the current permission, approval, trust, and security posture before changing policy or attempting risky work.',
        why: 'The request asks what permissions, approvals, policies, or safety status are active.',
        modelRoute: `security action:"status" query:${quote(request)} includeParameters:true`,
        inspectRoute: 'security action:"status" includeParameters:true',
        userRoute: '/security',
        requiresConfirmation: false,
        supportingRoutes: [
          'workspace action:"actions" categoryId:"tools-permissions"',
          'settings action:"list" query:"permissions approval policy" includeParameters:true',
          'security action:"finding" findingId:"..." includeParameters:true',
        ],
        policy: 'Security posture inspection is read-only. Permission changes, approval changes, and risky target actions remain separate confirmed routes.',
      });
    }

    if (securityFindingLike(lower)) {
      add({
        id: 'security-finding-inspection',
        label: 'Security finding inspection',
        score: 97,
        userSurface: 'Security panel',
        userOutcome: 'Inspect the exact security finding, trust issue, incident, or leaked-secret record before repair work.',
        why: 'The request asks to inspect a security finding, incident, vulnerability, trust warning, or secret-leak issue.',
        modelRoute: `security action:"finding" target:${quote(request)} includeParameters:true`,
        inspectRoute: 'security action:"status" includeParameters:true',
        userRoute: '/security',
        requiresConfirmation: false,
        supportingRoutes: [
          'security action:"status" includeParameters:true',
          'agent_harness mode:"security_finding" findingId:"..." includeParameters:true',
          'support action:"status" includeParameters:true',
        ],
        policy: 'Finding inspection returns redacted evidence only. Secret rotation, trust changes, MCP enablement, or file edits stay on explicit confirmed repair routes.',
      });
    }

    if (securityPolicyExplainLike(lower) || (!securityStatusLike(lower) && !securityFindingLike(lower))) {
      const explainTarget = securityPolicyToolTarget(lower);
      add({
        id: 'security-policy-explanation',
        label: 'Security policy explanation',
        score: securityPolicyExplainLike(lower) ? 100 : 90,
        userSurface: 'Security panel',
        userOutcome: 'Explain whether one model action is allowed, blocked, or waiting on confirmation before performing it.',
        why: 'The request asks about a tool, route, command, approval, confirmation, or why an action is allowed, denied, or blocked.',
        modelRoute: explainTarget
          ? `security action:"explain" target:${quote(explainTarget)} toolArgs:{...} includeParameters:true`
          : 'security action:"explain" toolName:"..." toolArgs:{...} includeParameters:true',
        inspectRoute: 'security action:"status" includeParameters:true',
        userRoute: '/security',
        requiresConfirmation: false,
        missingFields: explainTarget ? ['arguments or action details to explain'] : ['tool name or route id', 'arguments or action details to explain'],
        supportingRoutes: [
          'security action:"status" includeParameters:true',
          'security action:"finding" findingId:"..." includeParameters:true',
          'agent_harness mode:"policy_explain" toolName:"..." toolArgs:{...}',
        ],
        policy: 'Policy explanations are read-only and never execute the target tool. Final execution still uses the live route guard, permission prompt, and typed confirmation gate.',
      });
    }
  }

  if (supportBundleLike(lower)) {
    const bundleEffect = supportBundleEffectLike(lower);
    add({
      id: 'support-bundle-route',
      label: 'Support bundle and diagnostics packet route',
      score: 96,
      userSurface: 'Connected Host workspace',
      userOutcome: 'Inspect available redacted support, diagnostic, trust, auth, or forensic bundles before exporting or importing anything.',
      why: 'The request mentions support bundles, diagnostic bundles, forensic bundles, or support packets.',
      modelRoute: `support action:"status" query:${quote(request)} includeParameters:true`,
      inspectRoute: 'support action:"status" includeParameters:true',
      userRoute: 'Agent Workspace -> Connected Host -> Export support bundle',
      requiresConfirmation: bundleEffect,
      missingFields: bundleEffect ? ['bundle type or path', 'export/import/share destination when applicable', 'confirmation before bundle export, import, or external sharing'] : undefined,
      supportingRoutes: [
        'support action:"bundle" bundlePath:"..." includeParameters:true',
        'agent_harness mode:"support_bundles" includeParameters:true',
        'workspace action:"actions" query:"support bundle" includeParameters:true',
        'agent_harness mode:"run_workspace_action" actionId:"..." confirm:true explicitUserRequest:"..."',
      ],
      policy: 'Bundle catalog and bundle inspection are read-only and redacted. Bundle export, import, file writes, and sharing remain confirmation-gated workspace or slash-command flows.',
    });
  }

  if (sessionWorkspaceLike(lower) && !externalMemoryProviderLike(lower)) {
    const mutation = sessionMutationLike(lower);
    add({
      id: 'saved-session-route',
      label: 'Saved sessions, bookmarks, and transcript continuity',
      score: 97,
      userSurface: 'Conversation workspace',
      userOutcome: 'Find, inspect, resume, export, or manage saved Agent sessions and bookmarks from the conversation workspace.',
      why: 'The request mentions saved sessions, session search, transcript export, bookmarks, restore, or conversation continuity.',
      modelRoute: `sessions action:"list" query:${quote(request)} includeParameters:true`,
      inspectRoute: 'sessions action:"list" includeParameters:true',
      userRoute: 'Agent Workspace -> Conversation -> Search saved sessions',
      requiresConfirmation: mutation,
      missingFields: mutation ? ['session id, title, or search target', 'exact lifecycle action', 'confirmation before save/load/resume/rename/fork/export/delete/bookmark changes'] : undefined,
      supportingRoutes: [
        'sessions action:"list" query:"..." includeParameters:true',
        'sessions action:"get" sessionId:"..." includeParameters:true',
        'agent_harness mode:"sessions" includeParameters:true',
        'workspace action:"actions" categoryId:"conversation" query:"session" includeParameters:true',
        'agent_harness mode:"run_workspace_action" actionId:"session-save|session-load|session-export-saved|session-delete" confirm:true explicitUserRequest:"..."',
      ],
      policy: 'Session and bookmark inspection is read-only. Save, load, resume, rename, fork, export, delete, and bookmark writes stay visible and confirmed through workspace or slash-command routes.',
    });
  }

  if (releaseAuditLike(lower)) {
    const evidence = releaseEvidenceLike(lower);
    add({
      id: evidence ? 'release-evidence-route' : 'release-readiness-route',
      label: evidence ? 'Release evidence artifact route' : 'Release readiness inventory route',
      score: 96,
      userSurface: 'Operator/audit release artifacts',
      userOutcome: evidence
        ? 'Inspect packaged release evidence and operator/audit artifacts without expanding raw files blindly.'
        : 'Inspect the release-quality inventory, gates, and readiness dimensions before claiming a product capability is covered.',
      why: 'The request mentions release evidence, readiness inventory, release gates, verification ledger, or operator audit artifacts.',
      modelRoute: evidence
        ? `audit action:"evidence" query:${quote(request)} includeParameters:true`
        : `audit action:"readiness" query:${quote(request)} includeParameters:true`,
      inspectRoute: evidence
        ? 'audit action:"evidence" includeParameters:true'
        : 'audit action:"readiness" includeParameters:true',
      userRoute: 'release/ evidence files shipped in the package',
      requiresConfirmation: false,
      supportingRoutes: evidence
        ? [
          'audit action:"artifact" artifactId:"..." includeParameters:true',
          'audit action:"readiness" includeParameters:true',
          'agent_harness mode:"release_evidence" includeParameters:true',
        ]
        : [
          'audit action:"item" itemId:"..." includeParameters:true',
          'audit action:"evidence" includeParameters:true',
          'agent_harness mode:"release_readiness" includeParameters:true',
        ],
      policy: 'Release evidence and readiness inventory inspection are read-only. They expose packaged audit facts and bounded artifact content, not product mutations.',
    });
  }

  if (hasAny(lower, ['daemon method', 'operator method', 'host capability', 'service endpoint', 'control plane', 'api route'])) {
    add({
      id: 'connected-host-contract',
      label: 'Connected host capability or method contract',
      score: 78,
      userSurface: 'Connected host diagnostics',
      userOutcome: 'Inspect daemon capabilities through public contracts instead of guessing hidden routes.',
      why: 'The request asks about daemon/operator/API route capability or service posture.',
      modelRoute: 'host action:"capabilities" includeParameters:true',
      inspectRoute: 'host action:"methods" includeParameters:true',
      userRoute: 'Agent Workspace -> Start',
      requiresConfirmation: false,
      supportingRoutes: [
        'host action:"method" methodId:"..."',
        'agent_operator_method methodId:"..." confirm:true explicitUserRequest:"..."',
        'host action:"services" includeParameters:true',
      ],
      policy: 'Method discovery is read-only; write/admin daemon methods require exact method id, confirmation, and an explicit user request.',
    });
  }
}
