import { MODAL_TONES } from './modal-theme.ts';
import { infoRow } from './modal-surface-helpers.ts';
import type {
  ProjectPlanningDecision,
  ProjectPlanningLanguageArtifact,
  ProjectPlanningRevision,
  ProjectPlanningService,
  ProjectPlanningState,
  ProjectPlanningStatus,
} from '@goodvibes-jev/engine/sdk/platform/knowledge';
import type {
  ConfigModalActionContext,
  ConfigModalRow,
  ConfigModalSurface,
  ConfigModalView,
} from '../../input/config-modal-types.ts';

// This is a passive saved-record viewer. It never evaluates readiness, asks Jev
// for suggestions, edits a record, or submits native input. Explicit historical
// editing and native intake/recovery remain separate command paths.
const HISTORICAL_TITLE = 'Historical planning';
const HISTORICAL_BOUNDARY = 'Historical approval does not grant native execution or migrate records.';

export type PlanningModalService = Pick<ProjectPlanningService, 'status' | 'getState' | 'listDecisions' | 'getLanguage'>;

export interface PlanningModalDeps {
  readonly service: PlanningModalService;
  readonly projectId: string;
  readonly requestRender?: () => void;
}

interface PlanningModalSnapshot {
  readonly status: ProjectPlanningStatus | null;
  readonly state: ProjectPlanningState | null;
  readonly revision: ProjectPlanningRevision | null;
  readonly decisions: readonly ProjectPlanningDecision[];
  readonly language: ProjectPlanningLanguageArtifact | null;
}

interface TextLine { readonly content: string; readonly fg?: string; }

function buildStateLines(state: ProjectPlanningState): TextLine[] {
  const lines: TextLine[] = [
    { content: `saved readiness ${state.readiness}  historical approval ${state.executionApproved ? 'yes' : 'no'}` },
    { content: `questions ${state.openQuestions.length} saved / ${state.answeredQuestions.length} answered  tasks ${state.tasks.length}  gates ${state.verificationGates.length}` },
    { content: `goal: ${state.goal || '(not set)'}` },
  ];
  if (state.scope) lines.push({ content: `scope: ${state.scope}` });
  for (const [label, values] of [['known context', state.knownContext], ['assumptions', state.assumptions], ['constraints', state.constraints], ['risks', state.risks]] as const) {
    if (values.length) lines.push({ content: `${label}: ${values.join(' | ')}` });
  }
  return lines;
}

function buildQuestionLines(state: ProjectPlanningState): TextLine[] {
  const lines: TextLine[] = [{ content: 'Saved questions and answers:' }];
  if (!state.openQuestions.length && !state.answeredQuestions.length) {
    lines.push({ content: '  No saved questions. No new question is generated by this view.', fg: MODAL_TONES.dim });
  }
  for (const question of [...state.openQuestions, ...state.answeredQuestions]) {
    lines.push({ content: `  ${question.id}: ${question.prompt} [${question.status ?? 'open'}]` });
    if (question.whyItMatters) lines.push({ content: `    saved context: ${question.whyItMatters}` });
    if (question.recommendedAnswer) lines.push({ content: `    saved recommendation: ${question.recommendedAnswer}` });
    if (question.consequence) lines.push({ content: `    saved consequence: ${question.consequence}` });
    if (question.answer !== undefined) lines.push({ content: `    answer: ${question.answer}` });
    if (question.metadata) lines.push({ content: `    saved metadata: ${JSON.stringify(question.metadata)}` });
  }
  return lines;
}

function buildTasksLines(state: ProjectPlanningState): TextLine[] {
  const lines: TextLine[] = [{ content: 'Task graph:' }];
  if (state.tasks.length === 0) {
    lines.push({ content: '  No decomposed tasks recorded yet.' });
  } else {
    for (const task of state.tasks) {
      lines.push({ content: `  ${task.id}: ${task.title} [${task.status ?? 'pending'}]${task.canRunConcurrently ? ' - concurrent' : ''}`, ...(task.blockedOnUserInput ? { fg: MODAL_TONES.warn } : {}) });
      if (task.dependencies?.length) lines.push({ content: `    dependencies: ${task.dependencies.join(', ')}` });
      if (task.metadata) lines.push({ content: `    saved metadata: ${JSON.stringify(task.metadata)}` });
      if (task.verification?.length) lines.push({ content: `    verification: ${task.verification.join(' | ')}`, fg: MODAL_TONES.good });
    }
  }
  if (state.verificationGates.length) {
    lines.push({ content: 'Verification gates:' });
    for (const gate of state.verificationGates) lines.push({ content: `  ${gate.id}: ${gate.description} [${gate.status ?? 'pending'}]`, fg: gate.required === false ? undefined : MODAL_TONES.good });
  }
  if (state.agentAssignments.length) {
    lines.push({ content: 'Agent handoff candidates:' });
    for (const assignment of state.agentAssignments) lines.push({ content: `  ${assignment.taskId}: ${assignment.agentType ?? 'none'}${assignment.canRunConcurrently ? ' - can run concurrently' : ''}`, fg: MODAL_TONES.info });
  }
  return lines;
}

function buildDecisionsLines(state: ProjectPlanningState | null, storedDecisions: readonly ProjectPlanningDecision[]): TextLine[] {
  const byId = new Map<string, ProjectPlanningDecision>();
  for (const decision of [...storedDecisions, ...(state?.decisions ?? [])]) byId.set(decision.id, decision);
  const decisions = [...byId.values()];
  if (decisions.length === 0) return [{ content: 'Decisions: none recorded yet.' }];
  return [{ content: 'Decisions:' }, ...decisions.map((decision) => ({ content: `  ${decision.title}: ${decision.decision} [${decision.status ?? 'accepted'}]`, fg: decision.status === 'rejected' ? MODAL_TONES.bad : undefined }))];
}

function buildLanguageLines(language: ProjectPlanningLanguageArtifact | null): TextLine[] {
  if (!language || (language.terms.length === 0 && language.ambiguities.length === 0)) return [{ content: 'Project language: no terms or ambiguity resolutions recorded yet.' }];
  const lines: TextLine[] = [{ content: 'Project language:' }];
  for (const term of language.terms) {
    lines.push({ content: `  ${term.term}: ${term.definition}` });
    if (term.avoid?.length) lines.push({ content: `    avoid: ${term.avoid.join(', ')}`, fg: MODAL_TONES.bad });
  }
  for (const ambiguity of language.ambiguities) lines.push({ content: `  resolved ambiguity - ${ambiguity.phrase}: ${ambiguity.resolution}`, fg: MODAL_TONES.info });
  return lines;
}

class PlanningModalSurface implements ConfigModalSurface {
  readonly name = 'planning-modal';
  readonly title = HISTORICAL_TITLE;
  private snapshot: PlanningModalSnapshot | null = null;
  private loading = false;
  private generation = 0;
  private controller: AbortController | null = null;
  private requestRender: () => void = () => {};

  constructor(private readonly deps: PlanningModalDeps) {}

  readonly actions = [{ key: 'r', id: 'refresh', label: 'refresh' }];

  onOpen(requestRender: () => void): void { this.requestRender = requestRender; this.refresh(); }

  onClose(): void {
    this.controller?.abort();
    this.controller = null;
    this.generation++;
    this.loading = false;
    this.snapshot = null;
  }

  private repaint(): void { this.requestRender(); this.deps.requestRender?.(); }

  private refresh(): void {
    this.controller?.abort();
    const controller = new AbortController();
    this.controller = controller;
    const generation = ++this.generation;
    this.loading = true;
    this.snapshot = null;
    void this.load(generation, controller.signal);
  }

  private current(generation: number, signal: AbortSignal): boolean {
    return generation === this.generation && !signal.aborted;
  }

  private async load(generation: number, signal: AbortSignal): Promise<void> {
    try {
      const [status, stateResult, decisionsResult, languageResult] = await Promise.all([
        this.deps.service.status({ projectId: this.deps.projectId }),
        this.deps.service.getState({ projectId: this.deps.projectId }),
        this.deps.service.listDecisions({ projectId: this.deps.projectId }),
        this.deps.service.getLanguage({ projectId: this.deps.projectId }),
      ]);
      if (!this.current(generation, signal)) return;
      const snapshot: PlanningModalSnapshot = {
        status, state: stateResult.state ? structuredClone(stateResult.state) : null,
        revision: stateResult.revision ? Object.freeze({ ...stateResult.revision }) : null,
        decisions: structuredClone(decisionsResult.decisions), language: languageResult.language ? structuredClone(languageResult.language) : null,
      };
      this.snapshot = snapshot;
      this.loading = false;
      this.repaint();
    } catch {
      if (!this.current(generation, signal)) return;
      this.snapshot = null;
      this.loading = false;
      this.repaint();
    }
  }

  buildView(): ConfigModalView {
    // This view has no selected action to preserve across refresh. Bind the
    // host to the read phase so completed reads replace stale/frozen rows.
    const bindingIdentity = `planning-history:${this.generation}:${this.snapshot ? 'saved' : this.loading ? 'loading' : 'unavailable'}`;
    if (!this.snapshot) {
      return { title: HISTORICAL_TITLE, bindingIdentity, tabs: [{ id: 'planning', label: 'History', header: [HISTORICAL_BOUNDARY], rows: [infoRow('load', this.loading ? 'Loading historical planning records...' : 'Historical planning records unavailable.', { fg: MODAL_TONES.dim })] }], hints: ['r refresh'] };
    }

    const { status, state, revision, decisions, language } = this.snapshot;
    const header = [
      `project ${this.deps.projectId}  space ${status?.knowledgeSpaceId ?? `project:${this.deps.projectId}`}`,
      HISTORICAL_BOUNDARY,
    ];
    const rows: ConfigModalRow[] = [];
    let n = 0;
    const line = (l: TextLine): void => { rows.push({ id: `p:${n++}`, label: l.content, selectable: false, ...(l.fg ? { style: { fg: l.fg } } : {}) }); };

    if (!state) {
      line({ content: 'No historical planning state has been saved for this workspace.' });
      line({ content: 'Start native work with /project-plan <goal>; /project-plan opens the native work ledger.', fg: undefined });
      for (const l of buildDecisionsLines(null, decisions)) line(l);
      for (const l of buildLanguageLines(language)) line(l);
      return { title: HISTORICAL_TITLE, bindingIdentity, scrollInformationalLines: true, tabs: [{ id: 'planning', label: 'History', header, rows, emptyText: '' }], hints: ['r refresh'] };
    }

    for (const l of buildStateLines(state)) line(l);

    if (revision) line({ content: `saved revision: ${revision.sourceId} ${revision.generation}`, fg: MODAL_TONES.dim });
    for (const l of buildQuestionLines(state)) line(l);
    for (const l of buildTasksLines(state)) line(l);
    for (const l of buildDecisionsLines(state, decisions)) line(l);
    for (const l of buildLanguageLines(language)) line(l);
    if (state.metadata) line({ content: `Saved metadata (including artifact/link and approval provenance): ${JSON.stringify(state.metadata)}` });
    line({ content: 'Read-only history. New work and recovery: /project-plan. Import remains a separate explicit operation.', fg: MODAL_TONES.dim });

    return {
      title: HISTORICAL_TITLE,
      bindingIdentity,
      scrollInformationalLines: true,
      tabs: [{ id: 'planning', label: 'History', header, rows }],
      hints: ['r refresh'],
    };
  }

  onAction(id: string, ctx: ConfigModalActionContext): void {
    if (id === 'refresh') { this.refresh(); ctx.setStatus('Reloading historical planning records…'); }
    // Old submit/approve/dismiss IDs are intentionally inert, including stale
    // host events. Closing history is not cancellation of native work.
  }

}

export function createPlanningModalSurface(deps: PlanningModalDeps): ConfigModalSurface {
  return new PlanningModalSurface(deps);
}
