import type { AgentWorkspaceCategory } from './agent-workspace-types.ts';
import { settingAction } from './agent-workspace-category-actions.ts';
import { AGENT_WORKSPACE_HOST_CATEGORY } from './agent-workspace-host-category.ts';
import { AGENT_WORKSPACE_ONBOARDING_DETAIL_CATEGORIES } from './agent-workspace-onboarding-categories.ts';
import { THEME_MODE_CONFIG_KEY } from '../renderer/theme-mode-config.ts';

export const AGENT_WORKSPACE_CATEGORIES: readonly AgentWorkspaceCategory[] = [
  {
    id: 'home',
    group: 'START',
    label: 'Home',
    summary: 'Everything the assistant can do, one lane per kind of work.',
    detail: 'Pick the lane that matches what you want, or just close this and type. Every page here is also reachable later.',
    actions: [
      { id: 'chat', label: 'Just start typing', detail: 'Close this workspace and ask for anything, research, reminders, email, documents, or scheduling.', kind: 'guidance', safety: 'safe' },
      { id: 'assistant-setup-lane', label: 'Finish setting up', detail: 'Sign in, pick a model, and connect the basics.', targetCategoryId: 'setup', kind: 'workspace', safety: 'safe' },
      { id: 'assistant-personal-ops-lane', label: 'Inbox, calendar & reminders', detail: 'Daily personal operations in one place.', targetCategoryId: 'personal-ops', kind: 'workspace', safety: 'safe' },
      { id: 'assistant-research-docs-lane', label: 'Research something', detail: 'Web research with visible runs, sources, and saved reports.', targetCategoryId: 'research', kind: 'workspace', safety: 'safe' },
      { id: 'assistant-documents-lane', label: 'Documents & files', detail: 'Drafts, exports, saved files, and model comparisons.', targetCategoryId: 'documents', kind: 'workspace', safety: 'safe' },
      { id: 'assistant-automation-lane', label: 'Schedules & automation', detail: 'Reminders, routines, and scheduled work.', targetCategoryId: 'automation', kind: 'workspace', safety: 'safe' },
      { id: 'assistant-messaging-lane', label: 'Messaging & notifications', detail: 'Connect Slack, Discord, Telegram, and more; send messages and notifications.', targetCategoryId: 'onboarding-channels', kind: 'workspace', safety: 'safe' },
      { id: 'assistant-memory-lane', label: 'Memory & personality', detail: 'What the assistant remembers and how it behaves.', targetCategoryId: 'memory', kind: 'workspace', safety: 'safe' },
      { id: 'assistant-work-lane', label: 'Approvals & running work', detail: 'Pending approvals, background processes, and host tasks.', targetCategoryId: 'work', kind: 'workspace', safety: 'read-only' },
      { id: 'mode-preset', label: 'Set interaction mode', detail: 'Choose quiet, balanced, or operator mode for how much the assistant checks in.', editorKind: 'mode-preset', kind: 'editor', safety: 'safe' },
    ],
  },
  {
    id: 'setup',
    group: 'ONBOARDING',
    label: 'Start',
    summary: 'Pick a model to start, use a local one or sign in to a provider.',
    detail: 'Start here on a fresh install. Every row either saves state, opens the shared model picker, or opens a confirmed in-modal form.',
    actions: [
      // Working-path choices first, local (no sign-in needed) then provider sign-in.
      { id: 'use-local-model', label: 'Use a local model (no sign-in)', detail: 'Opens the model picker, which recommends models that fit this computer. No account or subscription needed.', kind: 'model-picker', modelPickerFlow: 'model', modelPickerTarget: 'main', safety: 'safe' },
      { id: 'subscription-login-start', label: 'Sign in to a provider', detail: 'Start one provider sign-in flow, save pending state, and return here.', editorKind: 'subscription-login-start', kind: 'editor', safety: 'safe' },
      { id: 'subscription-login-finish', label: 'Finish provider sign-in', detail: 'Exchange a code or redirect URL and save the provider subscription session.', editorKind: 'subscription-login-finish', kind: 'editor', safety: 'safe' },
      { id: 'setup-provider-model', label: 'Choose main model', detail: 'Open the shared provider/model picker for normal assistant turns.', kind: 'model-picker', modelPickerFlow: 'providerModel', modelPickerTarget: 'main', safety: 'safe' },
      { id: 'import-goodvibes-tui-settings', label: 'Import GoodVibes settings', detail: 'Import compatible shared GoodVibes display, provider, subscription, behavior, permission, TTS, channel, helper, tool, release, and automation values into Agent-owned state.', kind: 'settings-import', safety: 'safe' },
      settingAction({ id: 'setup-reasoning-effort', label: 'Reasoning effort', detail: 'Cycle reasoning level when the selected model supports it.', key: 'provider.reasoningEffort' }),
      settingAction({ id: 'setup-save-history', label: 'Save history', detail: 'Toggle local conversation history persistence.', key: 'behavior.saveHistory' }),
      // Less common controls
      { id: 'subscription-logout', label: 'Sign out of a provider', detail: 'Remove one stored or pending provider subscription session after confirmation.', editorKind: 'subscription-logout', kind: 'editor', safety: 'safe' },
      { id: 'provider-add', label: 'Add a custom provider', detail: 'Add one OpenAI-compatible provider for Agent model routing.', editorKind: 'provider-add', kind: 'editor', safety: 'safe' },
      { id: 'secret-set-provider', label: 'Store a credential', detail: 'Store a provider or channel credential through the Agent secret manager.', editorKind: 'secret-set', kind: 'editor', safety: 'safe' },
      settingAction({ id: 'setup-secret-policy', label: 'Secret storage policy', detail: 'Choose how strongly Agent prefers secure secret storage.', key: 'storage.secretPolicy' }),
      // Resume-point controls (rare; only matters when onboarding is split across sessions)
      { id: 'setup-checkpoint-show', label: 'Show saved resume point', detail: 'Inspect the saved setup wizard resume point without writing setup state.', setupCheckpointOperation: 'show', kind: 'setup-checkpoint', safety: 'read-only' },
      { id: 'setup-checkpoint-mark-current', label: 'Save resume point', detail: 'Save the current setup wizard step as the Agent-owned resume point for the next launch.', setupCheckpointOperation: 'mark-current', kind: 'setup-checkpoint', safety: 'safe' },
      { id: 'setup-checkpoint-clear', label: 'Clear saved resume point', detail: 'Clear the saved setup wizard resume point after setup is complete or no longer useful.', setupCheckpointOperation: 'clear', kind: 'setup-checkpoint', safety: 'safe' },
      { id: 'setup-skip-to-chat', label: 'Just start chatting (set up later)', detail: 'Close setup and go to the conversation. You can finish setup anytime with /agent.', kind: 'guidance', safety: 'safe' },
    ],
  },
  {
    id: 'account-model',
    group: 'ONBOARDING',
    label: 'Models',
    summary: 'Pick the chat model. Helper, tool, and spoken-turn routes are optional.',
    detail: 'Use this after sign-in. Most users only need the top row; the rest are advanced.',
    actions: [
      // Essentials, chat route + reasoning
      { id: 'provider-use', label: 'Choose provider and model', detail: 'Open the shared provider/model picker for the main chat route.', kind: 'model-picker', modelPickerFlow: 'providerModel', modelPickerTarget: 'main', safety: 'safe' },
      settingAction({ id: 'account-reasoning', label: 'Reasoning effort', detail: 'Cycle the reasoning effort used when supported.', key: 'provider.reasoningEffort' }),
      // Advanced routes, most people can skip these
      { id: 'account-advanced-separator', label: 'Advanced routes (optional), most people can skip these', detail: 'Helper, tool, TTS, embedding, system-prompt, and cache routing are here when you need them. Chat works without any of these.', kind: 'guidance', safety: 'read-only' },
      settingAction({ id: 'account-embedding', label: 'Embedding provider', detail: 'Set the embedding provider for memory and retrieval.', key: 'provider.embeddingProvider' }),
      settingAction({ id: 'account-provider-fallback-hint', label: 'Provider failure hints', detail: 'Toggle alternative model suggestions when the current provider fails non-transiently.', key: 'behavior.suggestAlternativeOnProviderFail' }),
      // Helper / tool / spoken-turn routes (advanced, only matters when you want dedicated routing)
      settingAction({ id: 'account-helper-enabled', label: 'Use a dedicated helper model', detail: 'Toggle a separate route for background utility work like summaries and titling.', key: 'helper.enabled' }),
      { id: 'account-helper-provider', label: 'Choose helper model', detail: 'Pick the provider and model for helper routing.', kind: 'model-picker', modelPickerFlow: 'providerModel', modelPickerTarget: 'helper', visibleWhenSettingKey: 'helper.enabled', visibleWhenSettingValue: true, safety: 'safe' },
      settingAction({ id: 'account-tool-llm-enabled', label: 'Use a dedicated tool model', detail: 'Toggle a separate route for internal tool calls.', key: 'tools.llmEnabled' }),
      { id: 'account-tool-provider', label: 'Choose tool model', detail: 'Pick the provider and model for dedicated tool calls.', kind: 'model-picker', modelPickerFlow: 'providerModel', modelPickerTarget: 'tool', visibleWhenSettingKey: 'tools.llmEnabled', visibleWhenSettingValue: true, safety: 'safe' },
      { id: 'account-tts-llm-provider', label: 'Choose spoken-turn model', detail: 'Pick the provider and model for spoken-response turns.', kind: 'model-picker', modelPickerFlow: 'providerModel', modelPickerTarget: 'tts', safety: 'safe' },
      // System prompt + custom provider plumbing
      settingAction({ id: 'account-system-prompt', label: 'Custom system prompt file', detail: 'Optional local file used as the system prompt for every assistant turn.', key: 'provider.systemPromptFile' }),
      { id: 'provider-remove', label: 'Remove a custom provider', detail: 'Remove one custom provider config after confirmation.', editorKind: 'provider-remove', kind: 'editor', safety: 'safe' },
      { id: 'account-run-local-model-benchmark', label: 'Run a local model benchmark', detail: 'Run the confirmed local-route benchmark through blind comparison, save latency/task-fit evidence, and keep model changes separate.', editorKind: 'local-model-benchmark', kind: 'editor', safety: 'safe' },
      // Prompt cache controls (advanced, most users leave defaults)
      settingAction({ id: 'account-cache-enabled', label: 'Prompt cache', detail: 'Toggle prompt caching for eligible providers.', key: 'cache.enabled' }),
      settingAction({ id: 'account-cache-ttl', label: 'Cache TTL', detail: 'Cycle ephemeral or persistent cache TTL for stable content.', key: 'cache.stableTtl', visibleWhenKey: 'cache.enabled', visibleWhenValue: true }),
      settingAction({ id: 'account-cache-monitor', label: 'Cache hit-rate monitor', detail: 'Toggle cache hit-rate monitoring.', key: 'cache.monitorHitRate', visibleWhenKey: 'cache.enabled', visibleWhenValue: true }),
      settingAction({ id: 'account-cache-threshold', label: 'Cache warning threshold', detail: 'Set the cache hit-rate warning threshold.', key: 'cache.hitRateWarningThreshold', visibleWhenKey: 'cache.monitorHitRate', visibleWhenValue: true }),
    ],
  },
  {
    id: 'assistant-behavior',
    group: 'ONBOARDING',
    label: 'Behavior',
    summary: 'Set interaction style, context pressure behavior, and visible reasoning.',
    detail: 'Use this to choose how chat feels during normal work and long-running tasks.',
    actions: [
      settingAction({ id: 'behavior-hitl-mode', label: 'Interaction mode', detail: 'Cycle quiet, balanced, or operator interaction mode.', key: 'behavior.hitlMode' }),
      settingAction({ id: 'behavior-guidance-mode', label: 'Guidance mode', detail: 'Cycle off, minimal, or guided operational guidance.', key: 'behavior.guidanceMode' }),
      settingAction({ id: 'behavior-auto-compact', label: 'Auto-compact threshold', detail: 'Set the context percentage that triggers automatic compaction.', key: 'behavior.autoCompactThreshold' }),
      settingAction({ id: 'behavior-stale-context', label: 'Context warnings', detail: 'Toggle proactive warnings before compaction is required.', key: 'behavior.staleContextWarnings' }),
      settingAction({ id: 'behavior-notify-complete', label: 'Notify on long turns', detail: 'Toggle terminal and desktop notification when a long turn completes.', key: 'behavior.notifyOnComplete' }),
      settingAction({ id: 'behavior-notifications-metadata-only', label: 'Notifications: metadata only', detail: 'Toggle whether notifications leave out the turn name, failure reasons, commands and file paths. Off by default, so notifications name the work they are about.', key: 'behavior.notificationsMetadataOnly' }),
      settingAction({ id: 'behavior-return-context', label: 'Resume summary mode', detail: 'Cycle off, local, or assisted resume summaries.', key: 'behavior.returnContextMode' }),
      settingAction({ id: 'behavior-show-thinking', label: 'Show thinking blocks', detail: 'Toggle visible reasoning/thinking content when the provider returns it.', key: 'display.showThinking' }),
      settingAction({ id: 'behavior-show-reasoning-summary', label: 'Show reasoning summary', detail: 'Toggle visible reasoning summaries when supported.', key: 'display.showReasoningSummary' }),
    ],
  },
  {
    id: 'tools-permissions',
    group: 'ONBOARDING',
    label: 'Tools & Permissions',
    summary: 'Set approval policy and core file/shell/network permissions.',
    detail: 'Most users only need Permission mode and Auto-approve. The rest stay at safe defaults unless you change them.',
    actions: [
      // Top-level approval policy
      settingAction({ id: 'permissions-mode', label: 'Permission mode', detail: 'Cycle prompt, allow-all, or custom permission mode.', key: 'permissions.mode' }),
      settingAction({ id: 'permissions-auto-approve', label: 'Auto-approve tools', detail: 'Toggle automatic approval for all tool permission requests.', key: 'behavior.autoApprove' }),
      // Common per-tool overrides for file and shell work
      settingAction({ id: 'permissions-read', label: 'File reads', detail: 'Cycle allow, prompt, or deny for file read operations.', key: 'permissions.tools.read' }),
      settingAction({ id: 'permissions-write', label: 'File writes', detail: 'Cycle allow, prompt, or deny for file write operations.', key: 'permissions.tools.write' }),
      settingAction({ id: 'permissions-edit', label: 'File edits', detail: 'Cycle allow, prompt, or deny for edit and patch operations.', key: 'permissions.tools.edit' }),
      settingAction({ id: 'permissions-exec', label: 'Shell commands', detail: 'Cycle allow, prompt, or deny for shell execution.', key: 'permissions.tools.exec' }),
      settingAction({ id: 'permissions-fetch', label: 'Network fetches', detail: 'Cycle allow, prompt, or deny for outbound fetch requests.', key: 'permissions.tools.fetch' }),
      // MCP servers + secrets (forms that open inside the modal)
      { id: 'onboarding-mcp-server', label: 'Add an MCP server', detail: 'Add or update one MCP server with command, args, role, trust, env refs, paths, and hosts.', editorKind: 'mcp-server', kind: 'editor', safety: 'safe' },
      { id: 'onboarding-secret-link', label: 'Link a secret reference', detail: 'Link one config key to a goodvibes secret reference.', editorKind: 'secret-link', kind: 'editor', safety: 'safe' },
      { id: 'onboarding-secret-test', label: 'Test a secret reference', detail: 'Check one stored secret reference without printing the value.', editorKind: 'secret-test', kind: 'editor', safety: 'safe' },
      // Advanced, tool runtime limits and debugging
      settingAction({ id: 'tools-auto-heal', label: 'Tool auto-heal', detail: 'Toggle automatic syntax repair for precision write and edit operations.', key: 'tools.autoHeal' }),
      settingAction({ id: 'tools-token-budget', label: 'Tool token budget', detail: 'Set the default token budget for precision read operations.', key: 'tools.defaultTokenBudget' }),
      settingAction({ id: 'storage-artifact-limit', label: 'Artifact storage limit', detail: 'Set the maximum artifact size for file, URL, multipart, and raw upload ingest.', key: 'storage.artifacts.maxBytes' }),
      settingAction({ id: 'telemetry-raw-prompts', label: 'Raw prompt telemetry', detail: 'Toggle raw prompt and response telemetry; leave off unless debugging locally.', key: 'telemetry.includeRawPrompts' }),
    ],
  },
  {
    id: 'onboarding-display',
    group: 'ONBOARDING',
    label: 'Interface',
    summary: 'Display, streaming, message placement, and release channel.',
    detail: 'Use this page to make the terminal readable for daily operation.',
    actions: [
      settingAction({ id: 'display-stream', label: 'Stream tokens', detail: 'Toggle streaming assistant tokens as they arrive.', key: 'display.stream' }),
      settingAction({ id: 'display-theme', label: 'Theme', detail: 'Cycle the color theme: system (your terminal colors) or a bundled theme. Applies immediately.', key: 'display.theme' }),
      settingAction({ id: 'display-theme-mode', label: 'Theme mode', detail: 'Cycle auto, dark, or light for the terminal background. Forced dark/light apply immediately; switching to auto takes effect on the next launch, when it re-probes the terminal.', key: THEME_MODE_CONFIG_KEY }),
      settingAction({ id: 'display-line-numbers', label: 'Line numbers', detail: 'Cycle all, code-only, or off for assistant output line numbers.', key: 'display.lineNumbers' }),
      settingAction({ id: 'display-collapse-threshold', label: 'Collapse threshold', detail: 'Set the line count threshold for collapsed tool output.', key: 'display.collapseThreshold' }),
      settingAction({ id: 'display-token-speed', label: 'Token speed counter', detail: 'Toggle tokens-per-second while generating.', key: 'display.showTokenSpeed' }),
      settingAction({ id: 'display-tool-preview', label: 'Tool call preview', detail: 'Toggle partial tool-call preview while streaming.', key: 'display.showToolPreview' }),
      settingAction({ id: 'display-operational-messages', label: 'Operational messages', detail: 'Cycle panel (activity feed only), conversation, or both for tool and runtime messages.', key: 'ui.operationalMessages' }),
      settingAction({ id: 'display-system-messages', label: 'System messages', detail: 'Cycle panel (activity feed only), conversation, or both for system messages.', key: 'ui.systemMessages' }),
      settingAction({ id: 'display-release-channel', label: 'Release channel', detail: 'Cycle stable or preview for update flows.', key: 'release.channel' }),
    ],
  },
  ...AGENT_WORKSPACE_ONBOARDING_DETAIL_CATEGORIES,
  {
    id: 'personal-ops',
    group: 'DAY-TO-DAY',
    label: 'Personal Ops',
    summary: 'Inbox, agenda, notes, tasks, reminders, routines, and delivery.',
    detail: 'Use this as the daily operations hub. It gives one path for personal work while keeping missing email/calendar connectors explicit.',
    actions: [
      { id: 'personal-ops-map', label: 'Readiness map', detail: 'Use the detail pane and model route personal_ops action:"status" to see which personal operations lanes are ready, partial, or missing setup.', kind: 'guidance', safety: 'safe' },
      { id: 'personal-ops-briefing', label: 'Daily briefing plan', detail: 'Build one read-only briefing plan across inbox, agenda, tasks, reminders, routines, delivery, notes, and the autonomy queue before reading live personal data or sending anything.', kind: 'guidance', safety: 'read-only' },
      { id: 'personal-ops-queue', label: 'Review queue', detail: 'List saved inbox thread and calendar event review items, refreshable provider-read routes, and follow-up confirmation boundaries with personal_ops action:"queue".', kind: 'guidance', safety: 'read-only' },
      { id: 'personal-ops-intake', label: 'Request planner', detail: 'Use personal_ops action:"intake" query:"..." to turn an inbox, agenda, task, reminder, note, routine, or delivery request into the safest visible route.', kind: 'guidance', safety: 'read-only' },
      { id: 'personal-ops-autonomy-queue', label: 'Autonomy queue', detail: 'Inspect visible ongoing work, owners, status, and cancel or recovery routes before creating more background work.', kind: 'guidance', safety: 'read-only' },
      { id: 'personal-ops-inbox', label: 'Inbox workflows', detail: 'Connect your inbox (IMAP/SMTP) to enable email triage and draft review. Opens a stepped connect wizard; credentials are stored through the Agent secret manager.', editorKind: 'email-connect-wizard', kind: 'editor', safety: 'safe' },
      { id: 'personal-ops-google-connect', label: 'Connect Google', detail: 'The one to pick. Works out the shortest route by itself, a credential already stored, an OAuth client that only needs your consent, or the gcloud CLI for the project and APIs, and asks you for at most one thing: approving a consent link. Mail and calendar are requested together, so one approval covers both, and it finishes by reading your mailbox and calendar to prove the connection works.', editorKind: 'google-connect', kind: 'editor', safety: 'safe' },
      { id: 'personal-ops-google-status', label: 'Google connection status', detail: 'What Gmail and Calendar have configured, and, when a credential is stored, what it can actually do, proven by reading the mailbox and the calendar. Reads only; no credential is shown.', editorKind: 'google-status', kind: 'editor', safety: 'read-only' },
      { id: 'personal-ops-google-reauthorize', label: 'Re-authorize Google', detail: 'Ask for a fresh Google consent covering mail and calendar together. Use this when something reports a missing scope or a credential has stopped working. The existing OAuth client is reused, so there is no project or console work, one consent link to approve, and nothing is deleted.', editorKind: 'google-reauthorize', kind: 'editor', safety: 'safe' },
      { id: 'personal-ops-google-forget', label: 'Remove stored Google credentials', detail: 'Remove the Google refresh token, OAuth client secret, Gmail app password and private calendar address from the encrypted store. Cannot be undone, the refresh token comes back only by approving a consent screen again. Requires an explicit confirmation and names exactly what was removed.', editorKind: 'google-forget', kind: 'editor', safety: 'safe' },
      { id: 'personal-ops-google-app-password', label: 'Connect Google (app password)', detail: 'The fast lane: an app password for mail over IMAP/SMTP plus the private iCal address for read-only calendar. No Cloud project and nothing that expires. Opens a browser and pauses for you to sign in, because Google refuses automated sign-in.', editorKind: 'google-setup-app-password', kind: 'editor', safety: 'safe' },
      { id: 'personal-ops-google-oauth', label: 'Connect Google (guided OAuth)', detail: 'The full walkthrough, project, consent screen, client, authorization, driven for you in the Google console. This is the path that enables calendar writes. Opens a browser and pauses for you to sign in.', editorKind: 'google-setup-walkthrough', kind: 'editor', safety: 'safe' },
      { id: 'personal-ops-google-adopt', label: 'Adopt existing Google credentials', detail: 'Take up a Google OAuth client and refresh token another tool already left on this machine (~/.gmail-mcp) instead of setting one up again. The files are read, never modified.', editorKind: 'google-adopt', kind: 'editor', safety: 'safe' },
      { id: 'personal-ops-google-client-file', label: 'Use a downloaded client JSON', detail: 'Point at an OAuth client JSON you already downloaded from the Google console and run the OAuth flow from it.', editorKind: 'google-client-file', kind: 'editor', safety: 'safe' },
      { id: 'personal-ops-google-client-manual', label: 'Paste a Google client id and secret', detail: 'Enter an OAuth client id and secret copied from the Google console. The secret is stored through the Agent secret manager and never rendered back.', editorKind: 'google-client-manual', kind: 'editor', safety: 'safe' },
      { id: 'personal-ops-calendar', label: 'Subscribe to a calendar', detail: 'Subscribe to an external calendar by its iCalendar (.ics) feed URL, Google "Secret address in iCal format", an Outlook published ICS link, or any .ics URL. Read-only, validated by fetching, merged into /calendar. The URL is stored through the Agent secret manager.', editorKind: 'calendar-subscribe-wizard', kind: 'editor', safety: 'safe' },
      { id: 'personal-ops-calendar-add', label: 'Add calendar event', detail: 'Add an event to the local Agent calendar with a stepped form (no external account required).', editorKind: 'calendar-connect', kind: 'editor', safety: 'safe' },
      { id: 'personal-ops-calendar-google', label: 'Connect Google Calendar (advanced)', detail: 'Full two-way sync via OAuth. Default path: just run /calendar connect google (bundled app + PKCE). This card is the advanced override to use your OWN Google OAuth client id; a client secret is stored through the Agent secret manager.', editorKind: 'calendar-oauth-google', kind: 'editor', safety: 'safe' },
      { id: 'personal-ops-calendar-outlook', label: 'Connect Microsoft Outlook (advanced)', detail: 'Full two-way sync via OAuth. Default path: just run /calendar connect outlook (bundled app + PKCE). This card is the advanced override to use your OWN Microsoft app registration; a client secret is stored through the Agent secret manager.', editorKind: 'calendar-oauth-outlook', kind: 'editor', safety: 'safe' },
      { id: 'personal-ops-notes', label: 'Scratchpad notes', detail: 'Open Agent-local notes for source triage, decisions, and handoff context.', targetCategoryId: 'notes', kind: 'workspace', safety: 'safe' },
      { id: 'personal-ops-note-create', label: 'Create note', detail: 'Capture temporary context as an Agent-local scratchpad note.', editorKind: 'note', kind: 'editor', safety: 'safe' },
      { id: 'personal-ops-reminder', label: 'Create reminder', detail: 'Create one connected reminder schedule with real timing, optional delivery target, and explicit confirmation.', editorKind: 'reminder-schedule', kind: 'editor', safety: 'safe' },
      { id: 'personal-ops-routines', label: 'Routine library', detail: 'Open repeatable workflows and schedule-promotion readiness.', targetCategoryId: 'routines', kind: 'workspace', safety: 'safe' },
      { id: 'personal-ops-schedules', label: 'Schedules', detail: 'Inspect connected schedules and promotion receipts from the automation area.', targetCategoryId: 'automation', kind: 'workspace', safety: 'safe' },
      { id: 'personal-ops-channels', label: 'Delivery channels', detail: 'Open pairing and channel readiness before sending summaries, reminders, or follow-ups.', targetCategoryId: 'onboarding-channels', kind: 'workspace', safety: 'safe' },
      { id: 'personal-ops-operator-methods', label: 'Assistant service methods', detail: 'The model can inspect the live assistant service contract with host action:"methods" query:"task" or personal_ops action:"lane" for one lane.', kind: 'guidance', safety: 'read-only' },
    ],
  },
  {
    id: 'research',
    group: 'DAY-TO-DAY',
    label: 'Research',
    summary: 'Read-only web research, visible runs, sources, and reports.',
    detail: 'Use this workspace to ask Agent to search, inspect URLs, track checkpointable research runs, compare sources, save sourced report artifacts, and decide what belongs in isolated Agent Knowledge. Research requests run in the normal conversation; source ingestion is explicit.',
    actions: [
      { id: 'research-main', label: 'Research in conversation', detail: 'Open a form that submits a read-only web research request to the main Agent conversation.', editorKind: 'web-research', kind: 'editor', safety: 'read-only' },
      { id: 'research-url', label: 'Inspect URL', detail: 'Open a form that submits one URL inspection task to the main Agent conversation without ingesting it.', editorKind: 'web-fetch', kind: 'editor', safety: 'read-only' },
      { id: 'research-briefing', label: 'Research briefing', detail: 'Show one read-only next-action queue across visible runs, source review, saved report artifacts, browser readiness, and confirmed follow-up routes with research action:"briefing".', kind: 'guidance', safety: 'read-only' },
      { id: 'research-workflow-plan', label: 'Plan workflow', detail: 'Inspect one ordered read-only plan across visible run state, browser-runner readiness, source review, visual-report packet save, and Knowledge promotion with research action:"plan"; use research action:"runner" for browser readiness only.', kind: 'guidance', safety: 'read-only' },
      { id: 'research-runner-readiness', label: 'Browser runner readiness', detail: 'Inspect the direct browser-backed runner contract, setup routes, fallback routes, and user-control requirements with research action:"runner" before treating live browser research as available.', kind: 'guidance', safety: 'read-only' },
      { id: 'research-run-queue', label: 'Research runs', detail: 'Inspect visible checkpointable research runs, phase, progress, resume, cancel, and report routes with research action:"runs".', kind: 'guidance', safety: 'read-only' },
      { id: 'research-public-search', label: 'Public source search', detail: 'Run bounded public web research and return capture-ready source candidates with research action:"search"; source queue writes still require explicit confirmation.', kind: 'guidance', safety: 'read-only' },
      { id: 'research-start-run', label: 'Start research run', detail: 'Open a confirmed form that creates one visible local research run with a resumable plan and no hidden background execution.', editorKind: 'research-run', kind: 'editor', safety: 'safe' },
      { id: 'research-source-queue', label: 'Source queue', detail: 'Inspect project-local source candidates, credibility, report-ready source lines, and safe review or ingest routes with research action:"sources".', kind: 'guidance', safety: 'read-only' },
      { id: 'research-add-source', label: 'Add source to queue', detail: 'Open a confirmed form that captures one source in the project-local research queue without saving a report or ingesting Knowledge.', editorKind: 'research-source', kind: 'editor', safety: 'safe' },
      { id: 'research-report-artifacts', label: 'Report artifacts', detail: 'List saved sourced research report artifacts, visual report packets, citation coverage metadata, and preview routes with research action:"reports".', kind: 'guidance', safety: 'read-only' },
      { id: 'research-save-report', label: 'Save research report', detail: 'Open a confirmed form that saves a reviewed source-grounded report artifact with a visual packet, source map, citation coverage, and handoff checklist. Use reviewed source queue lines when available.', editorKind: 'research-report', kind: 'editor', safety: 'safe' },
      { id: 'research-context-ref', label: 'Use URL as context', detail: 'From the composer, type @https://... to include a URL reference in a normal turn without ingesting it into Agent Knowledge.', kind: 'guidance', safety: 'read-only' },
      { id: 'research-knowledge-search', label: 'Search Agent Knowledge', detail: 'Search existing isolated Agent Knowledge before going to the web.', editorKind: 'knowledge-search', kind: 'editor', safety: 'read-only' },
      { id: 'research-knowledge-ask', label: 'Ask Agent Knowledge', detail: 'Ask isolated Agent Knowledge. It fails closed and never uses default knowledge or other knowledge segments.', editorKind: 'knowledge-ask', kind: 'editor', safety: 'read-only' },
      { id: 'research-note', label: 'Capture research note', detail: 'Create an Agent-local scratchpad note for source triage without ingesting it into Agent Knowledge.', editorKind: 'note', kind: 'editor', safety: 'safe' },
      { id: 'research-notes', label: 'Review notes', detail: 'Open scratchpad notes before deciding whether a source belongs in durable memory or Agent Knowledge.', targetCategoryId: 'notes', kind: 'workspace', safety: 'safe' },
      { id: 'research-ingest-url', label: 'Ingest URL into Agent Knowledge', detail: 'After reviewing a source, explicitly ingest it into isolated Agent Knowledge with typed confirmation.', editorKind: 'knowledge-url', kind: 'editor', safety: 'safe' },
      { id: 'research-import-urls', label: 'Import source URL list', detail: 'Import a reviewed local URL list into isolated Agent Knowledge with typed confirmation.', editorKind: 'knowledge-urls', kind: 'editor', safety: 'safe' },
      { id: 'research-web-policy', label: 'Research policy', detail: 'Web research is user-directed and serial. Agent should not silently ingest sources, send external messages, or mutate connected-host state from research requests.', kind: 'guidance', safety: 'blocked' },
    ],
  },
  {
    id: 'documents',
    group: 'DAY-TO-DAY',
    label: 'Documents & Files',
    summary: 'Draft docs, files, artifacts, and compare readiness.',
    detail: 'Use this workspace when the user is producing or evaluating a document. Versioned drafts, review comments, AI suggestion review, artifact insertion/export, upload, source, artifact browsing, media, and blind comparison routes stay visible here.',
    actions: [
      { id: 'document-ops-map', label: 'Readiness map', detail: 'Use agent_harness mode:"document_ops" to see document, reviewer-readiness, upload, export, source, media, artifact, and blind compare lanes.', kind: 'guidance', safety: 'read-only' },
      { id: 'document-browse-drafts', label: 'Browse document drafts', detail: 'List Agent-owned markdown drafts with status, version counts, tags, and exported artifact ids.', editorKind: 'document-browse', kind: 'editor', safety: 'read-only' },
      { id: 'document-show-draft', label: 'Show document draft', detail: 'Inspect one Agent-owned markdown draft with body and version history.', editorKind: 'document-show', kind: 'editor', safety: 'read-only' },
      { id: 'document-create-draft', label: 'Create document draft', detail: 'Open a confirmed form that saves a versioned Agent-owned markdown draft.', editorKind: 'document-create', kind: 'editor', safety: 'safe' },
      { id: 'document-revise-draft', label: 'Revise document draft', detail: 'Open a confirmed form that appends a new version to an Agent-owned markdown draft.', editorKind: 'document-update', kind: 'editor', safety: 'safe' },
      { id: 'document-review-draft', label: 'Mark draft reviewed', detail: 'Open a confirmed form that marks one Agent-owned markdown draft reviewed.', editorKind: 'document-review', kind: 'editor', safety: 'safe' },
      { id: 'document-comment-draft', label: 'Add review comment', detail: 'Open a confirmed form that adds one review comment without changing the document body.', editorKind: 'document-comment', kind: 'editor', safety: 'safe' },
      { id: 'document-resolve-comment', label: 'Resolve review comment', detail: 'Open a confirmed form that resolves one document review comment by id.', editorKind: 'document-resolve-comment', kind: 'editor', safety: 'safe' },
      { id: 'document-suggest-draft', label: 'Propose AI suggestion', detail: 'Open a confirmed form that stores a suggested replacement draft for review without changing the current document body.', editorKind: 'document-suggest', kind: 'editor', safety: 'safe' },
      { id: 'document-accept-suggestion', label: 'Accept suggestion', detail: 'Open a confirmed form that applies one pending document suggestion as a new content version.', editorKind: 'document-accept-suggestion', kind: 'editor', safety: 'safe' },
      { id: 'document-reject-suggestion', label: 'Reject suggestion', detail: 'Open a confirmed form that rejects one pending document suggestion without changing the document body.', editorKind: 'document-reject-suggestion', kind: 'editor', safety: 'safe' },
      { id: 'document-insert-artifact', label: 'Insert artifact in draft', detail: 'Open a confirmed form that inserts a saved artifact into one Agent-owned markdown draft as a new version.', editorKind: 'document-insert-artifact', kind: 'editor', safety: 'safe' },
      { id: 'document-attach-artifact', label: 'Attach artifact to draft', detail: 'Open a confirmed form that links a saved artifact to one document draft without changing the body.', editorKind: 'document-attach-artifact', kind: 'editor', safety: 'safe' },
      { id: 'document-review-packet-timeline', label: 'Review packet timeline', detail: 'Scan the chronological document, comment, suggestion, attachment, compare, judgment, handoff, archive, and route-decision timeline in this workspace context.', kind: 'guidance', safety: 'read-only' },
      { id: 'document-review-packet-wizard', label: 'Review packet wizard', detail: 'Open a read-only stepper for draft review, document export, comparison judgment, reviewer handoff, route decision, and final archive evidence.', editorKind: 'document-review-packet-wizard', kind: 'editor', safety: 'read-only' },
      { id: 'document-save-review-packet-preset', label: 'Save packet preset', detail: 'Open a confirmed form that saves the current document, comparison, judgment, handoff, archive, route decision, and related artifact ids as a reusable local preset artifact.', editorKind: 'document-review-packet-preset', kind: 'editor', safety: 'safe' },
      { id: 'document-refresh-review-packet-preset', label: 'Refresh packet preset', detail: 'Open a confirmed form that saves a new preset artifact from an existing stale packet preset and its freshness recommendations.', editorKind: 'document-review-packet-preset-refresh', kind: 'editor', safety: 'safe' },
      { id: 'document-share-review-packet', label: 'Share review packet', detail: 'Open a confirmed form that validates a saved reviewer handoff archive and sends a plain-text packet reference through one configured channel target.', editorKind: 'document-review-packet-share', kind: 'editor', safety: 'safe' },
      { id: 'document-reviewer-readiness', label: 'Review readiness preflight', detail: 'Open a read-only preflight that flags unresolved comments, proposed suggestions, source evidence gaps, unrevealed comparisons, route decisions, and handoff evidence before export, archive, or route update.', editorKind: 'document-reviewer-readiness', kind: 'editor', safety: 'read-only' },
      { id: 'document-export-draft', label: 'Export document artifact', detail: 'Open a confirmed form that exports one document draft as a markdown artifact.', editorKind: 'document-export', kind: 'editor', safety: 'safe' },
      { id: 'document-export-artifact-file', label: 'Export saved artifact', detail: 'Open a confirmed form that copies one saved artifact to a workspace file without printing content.', editorKind: 'artifact-export-file', kind: 'editor', safety: 'safe' },
      { id: 'document-export-artifact-package', label: 'Export artifact package', detail: 'Open a confirmed form that copies selected saved artifacts into a workspace package directory or ZIP archive with a redacted manifest.', editorKind: 'artifact-export-package', kind: 'editor', safety: 'safe' },
      { id: 'document-draft-chat', label: 'Draft in conversation', detail: 'Draft or revise a document in the main conversation, then export or save the resulting artifact through the visible export routes.', kind: 'guidance', safety: 'safe' },
      { id: 'document-attach-image', label: 'Attach image', detail: 'Open an in-workspace image attachment form for a local image path and optional document prompt.', editorKind: 'image-input', kind: 'editor', safety: 'safe' },
      { id: 'document-ingest-file', label: 'Ingest file source', detail: 'Open a confirmed form that imports one reviewed local file into isolated Agent Knowledge for document work.', editorKind: 'knowledge-file', kind: 'editor', safety: 'safe' },
      { id: 'document-ingest-url-list', label: 'Import URL list', detail: 'Open a confirmed form that imports a reviewed URL list into isolated Agent Knowledge.', editorKind: 'knowledge-urls', kind: 'editor', safety: 'safe' },
      { id: 'document-export-conversation', label: 'Export current conversation', detail: 'Open a confirmed form that exports the current Agent conversation to a workspace file.', editorKind: 'conversation-export', kind: 'editor', safety: 'safe' },
      { id: 'document-export-session', label: 'Export saved session', detail: 'Open a form that exports one saved Agent session transcript as markdown or text.', editorKind: 'session-export-saved', kind: 'editor', safety: 'read-only' },
      { id: 'document-show-source', label: 'Show source or node', detail: 'Open an in-workspace form that shows one Agent Knowledge source, node, or issue by id.', editorKind: 'knowledge-get', kind: 'editor', safety: 'read-only' },
      { id: 'document-browse-artifacts', label: 'Browse artifacts', detail: 'Search saved uploads, exports, generated media, source artifacts, and comparison artifacts from one read-only browser.', editorKind: 'artifact-browser', kind: 'editor', safety: 'read-only' },
      { id: 'document-show-artifact', label: 'Show artifact', detail: 'Inspect one saved artifact by id with redacted metadata and bounded text preview when possible.', editorKind: 'artifact-show', kind: 'editor', safety: 'read-only' },
      { id: 'document-promote-artifact', label: 'Promote artifact to Knowledge', detail: 'Open a confirmed form that ingests one saved artifact into isolated Agent Knowledge.', editorKind: 'artifact-promote-knowledge', kind: 'editor', safety: 'safe' },
      { id: 'document-generate-media', label: 'Generate media artifact', detail: 'Open a confirmed prompt form that generates image or video artifacts through configured media providers.', editorKind: 'media-generate', kind: 'editor', safety: 'safe' },
      { id: 'document-model-routing', label: 'Model routing', detail: 'Open provider/model route controls before any manual model comparison or route change.', targetCategoryId: 'account-model', kind: 'workspace', safety: 'safe' },
      { id: 'document-run-compare', label: 'Run blind compare', detail: 'Open a confirmed form that runs the same prompt or saved text artifact across two to four selectable models, hides candidate identities, and saves a review artifact.', editorKind: 'model-compare', kind: 'editor', safety: 'safe' },
      { id: 'document-review-compare', label: 'Review saved compare', detail: 'Open a read-only form that lists saved blind comparisons, renders one review board, shows related artifacts beside comparison evidence, or diffs two reviewer handoffs.', editorKind: 'model-compare-review', kind: 'editor', safety: 'read-only' },
      { id: 'document-diff-handoffs', label: 'Diff reviewer handoffs', detail: 'Open a split-pane read-only handoff diff form with section jump focus for all, metadata, policy, related artifacts, or comparison evidence.', editorKind: 'model-compare-handoff-diff', kind: 'editor', safety: 'read-only' },
      { id: 'document-judge-compare', label: 'Save compare judgment', detail: 'Open a confirmed form that saves the winning candidate and reasons as a local judgment artifact without changing model routing.', editorKind: 'model-compare-judge', kind: 'editor', safety: 'safe' },
      { id: 'document-compare-analytics', label: 'Compare analytics', detail: 'Summarize or synthesize saved comparison judgments by winner, model, blind slot, themes, task type, document id, benchmark tag, and recent reasons.', editorKind: 'model-compare-analytics', kind: 'editor', safety: 'read-only' },
      { id: 'document-apply-compare', label: 'Apply compare winner', detail: 'Open a confirmed form that applies a revealed saved comparison judgment to the main Agent model route.', editorKind: 'model-compare-apply', kind: 'editor', safety: 'safe' },
      { id: 'document-record-route-decision', label: 'Record route decision', detail: 'Open a confirmed form that records leave-current-model-unchanged evidence for a revealed comparison judgment.', editorKind: 'model-compare-route-decision', kind: 'editor', safety: 'safe' },
      { id: 'document-export-compare', label: 'Export compare report', detail: 'Open a confirmed form that exports a saved comparison or judgment report, creates a reviewer handoff with related artifacts, or archives a saved handoff as one ZIP artifact.', editorKind: 'model-compare-export', kind: 'editor', safety: 'safe' },
    ],
  },
  {
    id: 'conversation',
    group: 'DAY-TO-DAY',
    label: 'Conversation',
    summary: 'Transcript, prompt, context, and session controls.',
    detail: 'Use this workspace for the main TUI conversation: context review, compaction, prompt helpers, transcript navigation, session continuity, title, export, undo, redo, and retry.',
    actions: [
      { id: 'conversation-return', label: 'Return to composer', detail: 'Close the workspace and keep working in the main Agent conversation.', kind: 'guidance', safety: 'safe' },
      { id: 'conversation-context-refs', label: 'Context references', detail: 'Type @file, @folder, or @https://... in the composer to add bounded context to the main Agent turn. Use !@file only when you want raw file injection.', kind: 'guidance', safety: 'safe' },
      { id: 'conversation-save', label: 'Save current session', detail: 'Open a confirmed form that saves the current Agent session under a local name.', editorKind: 'session-save', kind: 'editor', safety: 'safe' },
      { id: 'conversation-load', label: 'Load saved session', detail: 'Open a confirmed form that loads one saved Agent session into the current conversation.', editorKind: 'session-load', kind: 'editor', safety: 'safe' },
      { id: 'conversation-rename', label: 'Rename this conversation', detail: 'Open a form that renames the current Agent session.', editorKind: 'session-rename', kind: 'editor', safety: 'safe' },
      { id: 'conversation-fork', label: 'Fork this conversation', detail: 'Open a form that branches the current conversation into a new saved session.', editorKind: 'session-fork', kind: 'editor', safety: 'safe' },
      { id: 'conversation-resume', label: 'Resume a saved conversation', detail: 'Open a form that resumes one saved Agent session by id, prefix, or title.', editorKind: 'session-resume', kind: 'editor', safety: 'safe' },
      { id: 'conversation-session-info', label: 'Inspect saved session', detail: 'Open a read-only form that prints saved-session metadata.', editorKind: 'session-info', kind: 'editor', safety: 'read-only' },
      { id: 'conversation-session-search', label: 'Search saved sessions', detail: 'Open a form that searches saved Agent sessions.', editorKind: 'session-search', kind: 'editor', safety: 'read-only' },
      { id: 'conversation-session-export', label: 'Export saved session', detail: 'Open a form that prints one saved-session transcript as markdown or text.', editorKind: 'session-export-saved', kind: 'editor', safety: 'read-only' },
      { id: 'conversation-session-delete', label: 'Delete saved session', detail: 'Open a confirmed form before deleting one saved Agent session.', editorKind: 'session-delete', kind: 'editor', safety: 'safe' },
      { id: 'conversation-export-current', label: 'Export current conversation', detail: 'Open a confirmed form that exports the current Agent conversation to a workspace file.', editorKind: 'conversation-export', kind: 'editor', safety: 'safe' },
      { id: 'conversation-controls-find', label: 'Find transcript text', detail: 'Open a search form for the current Agent transcript.', editorKind: 'conversation-find', kind: 'editor', safety: 'read-only' },
      { id: 'conversation-image', label: 'Attach image', detail: 'Open an in-workspace image form for attaching a real image path and optional prompt.', editorKind: 'image-input', kind: 'editor', safety: 'safe' },
      { id: 'conversation-tts', label: 'Speak a prompt', detail: 'Open an in-workspace prompt form for spoken assistant replies through configured live TTS.', editorKind: 'tts-prompt', kind: 'editor', safety: 'safe' },
    ],
  },
  {
    id: 'tools',
    group: 'CAPABILITIES',
    label: 'Tools & MCP',
    summary: 'MCP server setup, trust review, and tool inventory.',
    detail: 'Configure and inspect task tools from the Agent TUI. Adding or changing tools requires typed confirmation; normal chat still chooses tools serially in the main conversation.',
    actions: [
      { id: 'mcp-tools-server', label: 'Server tool inventory', detail: 'Open a server-name form for read-only MCP tool inventory from one server.', editorKind: 'mcp-tools-server', kind: 'editor', safety: 'read-only' },
      { id: 'mcp-add-server', label: 'Add MCP server', detail: 'Open a confirmed form that adds or updates one MCP server config with scope, role, trust, env refs, paths, and hosts.', editorKind: 'mcp-server', kind: 'editor', safety: 'safe' },
      { id: 'mcp-repair', label: 'Repair guidance', detail: 'Open a server-name form for read-only MCP repair guidance and next steps.', editorKind: 'mcp-repair', kind: 'editor', safety: 'read-only' },
      { id: 'secret-set', label: 'Store secret value', detail: 'Open a masked, confirmed form that stores one secret value through the Agent secret manager.', editorKind: 'secret-set', kind: 'editor', safety: 'safe' },
      { id: 'secret-link', label: 'Link secret ref', detail: 'Open a confirmed form that links one key to a goodvibes://secrets/... external reference.', editorKind: 'secret-link', kind: 'editor', safety: 'safe' },
      { id: 'secret-test', label: 'Test secret ref', detail: 'Open a confirmed form that tests one secret reference while printing only redacted status.', editorKind: 'secret-test', kind: 'editor', safety: 'safe' },
      { id: 'secret-delete', label: 'Delete secret', detail: 'Open a confirmed form that deletes one stored secret key from the selected scope and storage mode.', editorKind: 'secret-delete', kind: 'editor', safety: 'safe' },
      { id: 'trust-bundle-export', label: 'Export trust bundle', detail: 'Open a confirmed form that exports a redacted trust review bundle.', editorKind: 'trust-bundle-export', kind: 'editor', safety: 'safe' },
      { id: 'trust-bundle-inspect', label: 'Inspect trust bundle', detail: 'Open a form that inspects a trust review bundle before setup review.', editorKind: 'trust-bundle-inspect', kind: 'editor', safety: 'read-only' },
      { id: 'mcp-safety', label: 'Tool safety', detail: 'Agent may inspect and add reviewed MCP servers by explicit command, but will not silently install packages, change trust, or expose tools from ordinary chat.', kind: 'guidance', safety: 'blocked' },
    ],
  },
  {
    id: 'knowledge',
    group: 'CAPABILITIES',
    label: 'Knowledge',
    summary: 'Agent Knowledge and source-backed lookup.',
    detail: 'Agent knowledge calls use the isolated Agent Knowledge route family only. Default knowledge and non-Agent knowledge segments are not the Agent knowledge environment.',
    actions: [
      { id: 'knowledge-search', label: 'Search Agent knowledge', detail: 'Open an in-workspace search form for the isolated Agent Knowledge index.', editorKind: 'knowledge-search', kind: 'editor', safety: 'read-only' },
      { id: 'knowledge-ingest-url', label: 'Ingest URL', detail: 'Open an in-workspace form that ingests a real URL into Agent Knowledge only after typed confirmation.', editorKind: 'knowledge-url', kind: 'editor', safety: 'safe' },
      { id: 'knowledge-import-urls', label: 'Import URL list', detail: 'Open an in-workspace form that imports a local URL list into Agent Knowledge only after typed confirmation.', editorKind: 'knowledge-urls', kind: 'editor', safety: 'safe' },
      { id: 'knowledge-ingest-file', label: 'Ingest file', detail: 'Open an in-workspace form that imports a local file into Agent Knowledge only after typed confirmation.', editorKind: 'knowledge-file', kind: 'editor', safety: 'safe' },
      { id: 'knowledge-import-bookmarks', label: 'Import bookmarks', detail: 'Open an in-workspace form that imports a browser bookmark export into Agent Knowledge after typed confirmation.', editorKind: 'knowledge-bookmarks', kind: 'editor', safety: 'safe' },
      { id: 'knowledge-import-browser-history', label: 'Import browser history', detail: 'Open an in-workspace form that imports local browser history/bookmarks into Agent Knowledge after typed confirmation.', editorKind: 'knowledge-browser-history', kind: 'editor', safety: 'safe' },
      { id: 'knowledge-connector-show', label: 'Connector detail', detail: 'Open an in-workspace form that shows one Agent Knowledge connector by id.', editorKind: 'knowledge-connector-show', kind: 'editor', safety: 'read-only' },
      { id: 'knowledge-connector-doctor', label: 'Connector doctor', detail: 'Open an in-workspace form that runs a read-only readiness doctor for one Agent Knowledge connector.', editorKind: 'knowledge-connector-doctor', kind: 'editor', safety: 'read-only' },
      { id: 'knowledge-ingest-connector', label: 'Ingest connector input', detail: 'Open an in-workspace form for explicit connector input after checking connector readiness.', editorKind: 'knowledge-connector-ingest', kind: 'editor', safety: 'safe' },
      { id: 'knowledge-get', label: 'Show item', detail: 'Open an in-workspace form that shows one Agent Knowledge source, node, or issue by id.', editorKind: 'knowledge-get', kind: 'editor', safety: 'read-only' },
      { id: 'knowledge-map', label: 'Knowledge map', detail: 'Open an in-workspace form that summarizes the isolated Agent Knowledge graph map.', editorKind: 'knowledge-map', kind: 'editor', safety: 'read-only' },
      { id: 'knowledge-review-issue', label: 'Review issue', detail: 'Open a confirmed form that accepts, rejects, resolves, reopens, edits, or forgets one Agent Knowledge issue.', editorKind: 'knowledge-review-issue', kind: 'editor', safety: 'safe' },
      { id: 'knowledge-packet', label: 'Build prompt packet', detail: 'Open an in-workspace form that builds a compact Agent Knowledge prompt packet for a task.', editorKind: 'knowledge-packet', kind: 'editor', safety: 'read-only' },
      { id: 'knowledge-explain', label: 'Explain selection', detail: 'Open an in-workspace form that explains which Agent Knowledge context would be selected.', editorKind: 'knowledge-explain', kind: 'editor', safety: 'read-only' },
      { id: 'knowledge-consolidate', label: 'Consolidate knowledge', detail: 'Open a confirmed form that runs isolated Agent Knowledge consolidation.', editorKind: 'knowledge-consolidate', kind: 'editor', safety: 'safe' },
      { id: 'knowledge-reindex', label: 'Reindex Agent Knowledge', detail: 'Open a confirmed form that rebuilds the isolated Agent Knowledge index without touching default knowledge.', editorKind: 'knowledge-reindex', kind: 'editor', safety: 'safe' },
      { id: 'knowledge-ask', label: 'Ask Agent knowledge', detail: 'Open an in-workspace question form for isolated Agent Knowledge. Normal chat still uses the main conversation.', editorKind: 'knowledge-ask', kind: 'editor', safety: 'read-only' },
    ],
  },
  {
    id: 'profiles',
    group: 'LOCAL BEHAVIOR',
    label: 'Profiles',
    summary: 'Isolated Agent homes, starter templates, and setup bundles.',
    detail: 'Agent profiles isolate Agent state. Named homes and starter templates let one install behave like separate assistants for household, research, travel, operations, or personal workflows.',
    actions: [
      { id: 'runtime-profile-show', label: 'Show Agent profile', detail: 'Open a profile-name form that shows one isolated Agent profile home and starter metadata.', editorKind: 'profile-show', kind: 'editor', safety: 'read-only' },
      { id: 'runtime-profile-template-show', label: 'Preview starter', detail: 'Open an in-workspace form that previews one built-in or local starter template by id.', editorKind: 'profile-template-show', kind: 'editor', safety: 'read-only' },
      { id: 'runtime-profile-template-export', label: 'Export starter template', detail: 'Open an in-workspace form that exports a starter template JSON file for review and customization.', editorKind: 'profile-template-export', kind: 'editor', safety: 'safe' },
      { id: 'runtime-profile-template-import', label: 'Import starter template', detail: 'Open an in-workspace form that imports a reviewed starter template JSON file into this Agent home.', editorKind: 'profile-template-import', kind: 'editor', safety: 'safe' },
      { id: 'runtime-profile-create', label: 'Create Agent profile', detail: 'Open an in-workspace form that creates an isolated Agent home from a built-in or local starter.', editorKind: 'profile', kind: 'editor', safety: 'safe' },
      { id: 'runtime-profile-default', label: 'Use as default profile', detail: 'Select an isolated Agent profile for the next plain goodvibes-agent run. The current session keeps using its existing Agent home.', editorKind: 'profile-default', kind: 'editor', safety: 'safe' },
      { id: 'runtime-profile-clear-default', label: 'Clear default profile', detail: 'Return the next plain goodvibes-agent run to the base Agent home. The current session keeps using its existing Agent home.', editorKind: 'profile-default-clear', kind: 'editor', safety: 'safe' },
      { id: 'runtime-profile-delete', label: 'Delete Agent profile', detail: 'Open a confirmation form before deleting one isolated Agent profile home.', editorKind: 'profile-delete', kind: 'editor', safety: 'safe' },
      { id: 'runtime-profile-template-from-discovered', label: 'Starter from discovered behavior', detail: 'Open an in-workspace form that creates one local starter template from reviewed discovered persona, skill, and routine files.', editorKind: 'profile-template-from-discovered', kind: 'editor', safety: 'safe' },
      { id: 'runtime-profile-from-discovered', label: 'Profile from discovered behavior', detail: 'Open an in-workspace form that creates a local starter and isolated Agent profile from reviewed discovered behavior files.', editorKind: 'profile-from-discovered', kind: 'editor', safety: 'safe' },
      { id: 'runtime-profile-template-edit', label: 'Customize starter', detail: 'Open the starter export form, edit the JSON file, then import it as a local starter.', editorKind: 'profile-template-export', kind: 'editor', safety: 'safe' },
    ],
  },
  {
    // What the platform knows about HIM, distinct from `profiles` above, which
    // is isolated Agent HOMES. One Markdown file at daemon scope that he owns
    // and can edit by hand; his edits win and are never rewritten.
    //
    // The People section is counted in the overview, never listed: this card
    // renders inside a session, so what it prints is in the transcript a later
    // turn can compose from, the same reason the platform bars a bulk profile
    // read from a composition path (docs/owner-profile.md §10). Looking one
    // person up asks for the words he used that pointed at them.
    id: 'owner-profile',
    group: 'LOCAL BEHAVIOR',
    label: 'Your Profile',
    summary: 'What GoodVibes knows about you, and how to correct or forget a fact.',
    detail: 'Your name, how to reach you, where you live, where to ship things, how you like answers written, and the people, places and notes you have mentioned. It is one Markdown file the daemon keeps, open it and edit it by hand whenever you like; your edits win and are never rewritten. Facts the assistant learns from things you say directly to it are recorded as you say them, each carrying the surface, the date and your own words, and it tells you in one line what it recorded. Anything sourced from mail, a web page, a document, or a message from someone else is refused outright.',
    actions: [
      { id: 'owner-profile-read', label: 'What do you know about me', detail: 'Print the whole profile by section, with the surface, date and your own words on every learned line. People are counted rather than listed.', editorKind: 'owner-profile-read', kind: 'editor', safety: 'read-only' },
      { id: 'owner-profile-field', label: 'Show one field', detail: 'Print one field with its provenance. An unset field says so; a value that did not parse comes back as written, with the reason.', editorKind: 'owner-profile-get', kind: 'editor', safety: 'read-only' },
      { id: 'owner-profile-where', label: 'Where did you get that', detail: 'Trace one field: which surface recorded it, when, your exact words, and every earlier value still kept.', editorKind: 'owner-profile-provenance', kind: 'editor', safety: 'read-only' },
      { id: 'owner-profile-person', label: 'Look up one person', detail: 'Show what the profile records about one person, by name. There is no call that lists everyone, and this asks for the words you used that pointed at them.', editorKind: 'owner-profile-person', kind: 'editor', safety: 'read-only' },
      { id: 'owner-profile-correct', label: 'Correct a fact', detail: 'Write or correct one field. The previous value is kept as history, so a wrong correction can be put back.', editorKind: 'owner-profile-set', kind: 'editor', safety: 'safe' },
      { id: 'owner-profile-forget', label: 'Forget a fact', detail: 'Delete one field and every kept history comment for it. No tombstone and no retention window. Forgetting something that was not there says so.', editorKind: 'owner-profile-forget', kind: 'editor', safety: 'safe' },
      { id: 'owner-profile-forget-note', label: 'Forget a note or person', detail: 'Delete one prose line, a note, a person, a place, a work line, by giving it exactly as the profile reads it. Lines are named by content, never position, so a line you have since changed is not deleted by mistake.', editorKind: 'owner-profile-forget-note', kind: 'editor', safety: 'safe' },
      { id: 'owner-profile-status', label: 'Profile status', detail: 'Whether it loaded, where the file is, section names and counts, and any value that did not parse. Never prints a value.', editorKind: 'owner-profile-status', kind: 'editor', safety: 'read-only' },
      { id: 'owner-profile-settings', label: 'Profile settings', detail: 'Open the Your Profile settings category: whether the profile is kept at all, whether facts are recorded as you say them, whether it tells you what it recorded, and where the file lives.', command: '/settings', kind: 'command', safety: 'safe' },
    ],
  },
  {
    id: 'memory',
    group: 'LOCAL BEHAVIOR',
    label: 'Memory',
    summary: 'Local assistant memory, notes, routines, skills, and reusable behavior.',
    detail: 'Memory, notes, routines, skills, and personas stay Agent-local until stable shared registry contracts exist. Secrets must not be stored as memory or notes.',
    actions: [
      { id: 'memory-posture', label: 'Memory status', detail: 'Inspect Agent-local memory, prompt-active recall, vector health, embedding providers, and external-memory provider gaps with memory action:"status".', kind: 'guidance', safety: 'read-only' },
      { id: 'memory-search', label: 'Search memory', detail: 'Open an in-workspace Agent-local memory search form. This never queries default knowledge or other product routes.', editorKind: 'memory-search', kind: 'editor', safety: 'read-only' },
      { id: 'memory-get', label: 'Show memory by id', detail: 'Open an in-workspace form that prints one Agent-local memory record with provenance and links.', editorKind: 'memory-get', kind: 'editor', safety: 'read-only' },
      { id: 'memory-learning-curator', label: 'Learning curator', detail: 'Inspect ranked local memory, note, persona, skill, bundle, routine, duplicate-consolidation, completed-work, completed-research, and saved-session candidates with review, setup, stale, proposal, capture, diff, and rollback routes.', kind: 'guidance', safety: 'read-only' },
      { id: 'memory-prompt-plan', label: 'Prompt plan', detail: 'Explain which reviewed memories and setup-ready behaviors can guide the assistant now, what is suppressed, and which scored review routes should run before prompt context expands.', kind: 'guidance', safety: 'read-only' },
      { id: 'memory-explain', label: 'Explain selection', detail: 'Preview which reviewed Agent-local memories would be selected for a task.', editorKind: 'memory-explain', kind: 'editor', safety: 'read-only' },
      { id: 'memory-prev', label: 'Previous memory', detail: 'Move the local memory selection up without changing review state.', localKind: 'memory', selectionDelta: -1, kind: 'local-selection', safety: 'safe' },
      { id: 'memory-next', label: 'Next memory', detail: 'Move the local memory selection down without changing review state.', localKind: 'memory', selectionDelta: 1, kind: 'local-selection', safety: 'safe' },
      { id: 'memory-create', label: 'Create memory', detail: 'Open an in-workspace form for a durable, non-secret Agent memory. No default knowledge fallback is used.', editorKind: 'memory', kind: 'editor', safety: 'safe' },
      { id: 'notes-workspace', label: 'Scratchpad notes', detail: 'Open Agent-local notes for source triage, temporary decisions, and operator handoff.', targetCategoryId: 'notes', kind: 'workspace', safety: 'safe' },
      { id: 'note-create', label: 'Create note', detail: 'Open an in-workspace form for a local scratchpad note. This does not write memory or Agent Knowledge.', editorKind: 'note', kind: 'editor', safety: 'safe' },
      { id: 'learned-behavior', label: 'Capture learned behavior', detail: 'Turn a reviewed workflow, lesson, or operating style into one local skill, routine, or persona.', editorKind: 'learned-behavior', kind: 'editor', safety: 'safe' },
      { id: 'memory-edit', label: 'Edit selected memory', detail: 'Open the selected Agent memory in an in-workspace editor.', localKind: 'memory', localOperation: 'memory-edit', kind: 'local-operation', safety: 'safe' },
      { id: 'memory-review', label: 'Review selected', detail: 'Mark the selected Agent memory reviewed after inspecting it.', localKind: 'memory', localOperation: 'memory-review', kind: 'local-operation', safety: 'safe' },
      { id: 'memory-stale', label: 'Mark selected stale', detail: 'Mark the selected Agent memory stale so it stops being trusted until reviewed.', localKind: 'memory', localOperation: 'memory-stale', kind: 'local-operation', safety: 'safe' },
      { id: 'memory-delete', label: 'Delete selected memory', detail: 'Open a confirmation form before deleting the selected Agent memory.', localKind: 'memory', localOperation: 'memory-delete', kind: 'local-operation', safety: 'safe' },
      { id: 'memory-promote', label: 'Promote memory', detail: 'Open a confirmed form that promotes one Agent-local memory record to session, project, or team scope.', editorKind: 'memory-promote', kind: 'editor', safety: 'safe' },
      { id: 'memory-link', label: 'Link memories', detail: 'Open a confirmed form that links two Agent-local memory records with a directed relation.', editorKind: 'memory-link', kind: 'editor', safety: 'safe' },
      { id: 'memory-export', label: 'Export memory bundle', detail: 'Open a confirmed form that exports Agent-local memory records and links to a reviewable JSON bundle.', editorKind: 'memory-export', kind: 'editor', safety: 'safe' },
      { id: 'memory-import', label: 'Import memory bundle', detail: 'Open a confirmed form that imports a reviewed Agent-local memory bundle.', editorKind: 'memory-import', kind: 'editor', safety: 'safe' },
      { id: 'memory-handoff-export', label: 'Export handoff bundle', detail: 'Open a confirmed form that exports a scoped Agent-local memory handoff bundle.', editorKind: 'memory-handoff-export', kind: 'editor', safety: 'safe' },
      { id: 'memory-handoff-inspect', label: 'Inspect handoff bundle', detail: 'Open a form that inspects a memory handoff bundle before import.', editorKind: 'memory-handoff-inspect', kind: 'editor', safety: 'read-only' },
      { id: 'memory-handoff-import', label: 'Import handoff bundle', detail: 'Open a confirmed form that imports a reviewed handoff bundle into Agent-local memory.', editorKind: 'memory-handoff-import', kind: 'editor', safety: 'safe' },
      { id: 'memory-vector-rebuild', label: 'Rebuild vector index', detail: 'Open a confirmed form that rebuilds the Agent-local memory vector index.', editorKind: 'memory-vector-rebuild', kind: 'editor', safety: 'safe' },
      { id: 'personas', label: 'Persona library', detail: 'Open the local persona workspace for active role selection and review.', targetCategoryId: 'personas', kind: 'workspace', safety: 'safe' },
      { id: 'skills', label: 'Local skill library', detail: 'Open the local skill workspace for reusable procedures and review.', targetCategoryId: 'skills', kind: 'workspace', safety: 'safe' },
      { id: 'routines', label: 'Routine library', detail: 'Open the local routine workspace for repeatable workflows and schedule promotion review.', targetCategoryId: 'routines', kind: 'workspace', safety: 'safe' },
    ],
  },
  {
    id: 'notes',
    group: 'LOCAL BEHAVIOR',
    label: 'Notes',
    summary: 'Agent-local scratchpad for source triage and temporary context.',
    detail: 'Notes are local working context. They are useful for research notes, decisions in progress, and handoff notes, but they are not memory and are not Agent Knowledge.',
    actions: [
      { id: 'notes-guidance', label: 'How notes work', detail: 'Use notes to capture source triage and temporary context. Promote later by creating memory or explicitly ingesting a reviewed source into Agent Knowledge.', kind: 'guidance', safety: 'safe' },
      { id: 'notes-prev', label: 'Previous note', detail: 'Move the local note selection up without changing review state.', localKind: 'note', selectionDelta: -1, kind: 'local-selection', safety: 'safe' },
      { id: 'notes-next', label: 'Next note', detail: 'Move the local note selection down without changing review state.', localKind: 'note', selectionDelta: 1, kind: 'local-selection', safety: 'safe' },
      { id: 'notes-create', label: 'Create note', detail: 'Open an in-workspace form for a local scratchpad note that writes Agent-local state only.', editorKind: 'note', kind: 'editor', safety: 'safe' },
      { id: 'notes-edit', label: 'Edit selected', detail: 'Open the selected local note in an in-workspace editor.', localKind: 'note', localOperation: 'note-edit', kind: 'local-operation', safety: 'safe' },
      { id: 'notes-review', label: 'Review selected', detail: 'Mark the selected local note reviewed after inspecting it.', localKind: 'note', localOperation: 'note-review', kind: 'local-operation', safety: 'safe' },
      { id: 'notes-stale', label: 'Mark selected stale', detail: 'Mark the selected local note stale so it is not trusted as current.', localKind: 'note', localOperation: 'note-stale', kind: 'local-operation', safety: 'safe' },
      { id: 'notes-delete', label: 'Delete selected', detail: 'Open a confirmation form before deleting the selected Agent-local note.', localKind: 'note', localOperation: 'note-delete', kind: 'local-operation', safety: 'safe' },
      { id: 'notes-to-memory', label: 'Create memory from selected', detail: 'Prefill the memory form from the selected note. Saving writes memory only; the note remains unchanged.', localKind: 'note', localOperation: 'note-promote-memory', kind: 'local-operation', safety: 'safe' },
      { id: 'notes-to-skill', label: 'Create skill from selected', detail: 'Prefill a reusable skill from the selected note after reviewing a repeated procedure.', localKind: 'note', localOperation: 'note-promote-skill', kind: 'local-operation', safety: 'safe' },
      { id: 'notes-to-routine', label: 'Create routine from selected', detail: 'Prefill a repeatable main-conversation routine from the selected note.', localKind: 'note', localOperation: 'note-promote-routine', kind: 'local-operation', safety: 'safe' },
      { id: 'notes-to-persona', label: 'Create persona from selected', detail: 'Prefill a local operating persona from the selected note when it describes a durable style or role.', localKind: 'note', localOperation: 'note-promote-persona', kind: 'local-operation', safety: 'safe' },
      { id: 'notes-to-knowledge', label: 'Ingest reviewed source', detail: 'Prefill the Agent Knowledge URL ingest form from the selected note source URL.', localKind: 'note', localOperation: 'note-promote-knowledge-url', kind: 'local-operation', safety: 'safe' },
      { id: 'notes-research', label: 'Research source', detail: 'Open a read-only URL inspection form before deciding whether a source belongs in notes or Agent Knowledge.', editorKind: 'web-fetch', kind: 'editor', safety: 'read-only' },
    ],
  },
  {
    id: 'personas',
    group: 'LOCAL BEHAVIOR',
    label: 'Personas',
    summary: 'VIBE.md personality and local behavior profiles for the main assistant.',
    detail: 'VIBE.md is the friendly personality file for the serial Agent. Personas remain local behavior profiles, not separate Agent identities.',
    actions: [
      { id: 'personas-search', label: 'Search personas', detail: 'Open a search form for the local persona library.', editorKind: 'persona-search', kind: 'editor', safety: 'read-only' },
      { id: 'personas-show', label: 'Show persona', detail: 'Open a persona-id form for read-only local persona detail.', editorKind: 'persona-show', kind: 'editor', safety: 'read-only' },
      { id: 'personas-import-discovered', label: 'Import discovered persona', detail: 'Open an in-workspace form that imports one reviewed persona markdown file into the Agent-local persona registry after typed confirmation.', editorKind: 'persona-discovery-import', kind: 'editor', safety: 'safe' },
      { id: 'personas-prev', label: 'Previous persona', detail: 'Move the local persona selection up without changing active state.', localKind: 'persona', selectionDelta: -1, kind: 'local-selection', safety: 'safe' },
      { id: 'personas-next', label: 'Next persona', detail: 'Move the local persona selection down without changing active state.', localKind: 'persona', selectionDelta: 1, kind: 'local-selection', safety: 'safe' },
      { id: 'personas-create', label: 'Create persona', detail: 'Open an in-workspace form for a local persona that writes Agent-local state only.', editorKind: 'persona', kind: 'editor', safety: 'safe' },
      { id: 'personas-edit', label: 'Edit selected', detail: 'Open the selected local persona in an in-workspace editor.', localKind: 'persona', localOperation: 'persona-edit', kind: 'local-operation', safety: 'safe' },
      { id: 'personas-use', label: 'Use selected', detail: 'Activate the selected local persona for later main-conversation turns.', localKind: 'persona', localOperation: 'persona-use', kind: 'local-operation', safety: 'safe' },
      { id: 'personas-review', label: 'Review selected', detail: 'Mark the selected local persona reviewed after inspecting it.', localKind: 'persona', localOperation: 'persona-review', kind: 'local-operation', safety: 'safe' },
      { id: 'personas-clear', label: 'Clear active persona', detail: 'Return to the default Agent policy without deleting any persona.', localKind: 'persona', localOperation: 'persona-clear', kind: 'local-operation', safety: 'safe' },
      { id: 'personas-delete', label: 'Delete selected', detail: 'Open a confirmation form before deleting the selected local persona.', localKind: 'persona', localOperation: 'persona-delete', kind: 'local-operation', safety: 'safe' },
    ],
  },
  {
    id: 'skills',
    group: 'LOCAL BEHAVIOR',
    label: 'Skills',
    summary: 'Reusable local procedures with setup readiness.',
    detail: 'Skills are local, reviewable procedures with optional env/command requirements. Enabled skills inform the main conversation; secret-looking content is rejected.',
    actions: [
      { id: 'skills-search', label: 'Search skills', detail: 'Open a search form for Agent-local skills.', editorKind: 'skill-search', kind: 'editor', safety: 'read-only' },
      { id: 'skills-show', label: 'Show skill', detail: 'Open a skill-id form for read-only local skill detail.', editorKind: 'skill-show', kind: 'editor', safety: 'read-only' },
      { id: 'skills-import-discovered', label: 'Import discovered skill', detail: 'Open an in-workspace form that imports one reviewed discovered skill file into the Agent-local skill registry after typed confirmation.', editorKind: 'skill-discovery-import', kind: 'editor', safety: 'safe' },
      { id: 'skills-import-standard', label: 'Import a shared skill', detail: 'Import one SKILL.md file in the open skill format into the Agent-local skill library after review.', editorKind: 'skill-standard-import', kind: 'editor', safety: 'safe' },
      { id: 'skills-export-standard', label: 'Export skill to share', detail: 'Export one Agent-local skill as a SKILL.md folder you can publish or hand to another assistant.', editorKind: 'skill-standard-export', kind: 'editor', safety: 'safe' },
      { id: 'skills-create-bundle', label: 'Create bundle', detail: 'Open an in-workspace form that creates a named skill bundle from existing local skill ids.', editorKind: 'skill-bundle', kind: 'editor', safety: 'safe' },
      { id: 'skills-search-bundle', label: 'Search bundles', detail: 'Open an in-workspace form that searches Agent-local skill bundles.', editorKind: 'skill-bundle-search', kind: 'editor', safety: 'read-only' },
      { id: 'skills-show-bundle', label: 'Show bundle', detail: 'Open an in-workspace form that shows one Agent-local skill bundle by id.', editorKind: 'skill-bundle-show', kind: 'editor', safety: 'read-only' },
      { id: 'skills-update-bundle', label: 'Update bundle', detail: 'Open a confirmed form that updates one Agent-local skill bundle.', editorKind: 'skill-bundle-update', kind: 'editor', safety: 'safe' },
      { id: 'skills-enable-bundle', label: 'Enable bundle', detail: 'Open a confirmed form that enables one Agent-local skill bundle for main-conversation guidance.', editorKind: 'skill-bundle-enable', kind: 'editor', safety: 'safe' },
      { id: 'skills-disable-bundle', label: 'Disable bundle', detail: 'Open a confirmed form that disables one Agent-local skill bundle without deleting it.', editorKind: 'skill-bundle-disable', kind: 'editor', safety: 'safe' },
      { id: 'skills-review-bundle', label: 'Review bundle', detail: 'Open a confirmed form that marks one Agent-local skill bundle reviewed.', editorKind: 'skill-bundle-review', kind: 'editor', safety: 'safe' },
      { id: 'skills-stale-bundle', label: 'Mark bundle stale', detail: 'Open a confirmed form that marks one Agent-local skill bundle stale with a reason.', editorKind: 'skill-bundle-stale', kind: 'editor', safety: 'safe' },
      { id: 'skills-delete-bundle', label: 'Delete bundle', detail: 'Open a confirmation form before deleting one Agent-local skill bundle.', editorKind: 'skill-bundle-delete', kind: 'editor', safety: 'safe' },
      { id: 'skills-prev', label: 'Previous skill', detail: 'Move the local skill selection up without changing enabled state.', localKind: 'skill', selectionDelta: -1, kind: 'local-selection', safety: 'safe' },
      { id: 'skills-next', label: 'Next skill', detail: 'Move the local skill selection down without changing enabled state.', localKind: 'skill', selectionDelta: 1, kind: 'local-selection', safety: 'safe' },
      { id: 'skills-create', label: 'Create skill', detail: 'Open an in-workspace form for a reusable local procedure that writes Agent-local state only.', editorKind: 'skill', kind: 'editor', safety: 'safe' },
      { id: 'skills-edit', label: 'Edit selected', detail: 'Open the selected Agent-local skill in an in-workspace editor.', localKind: 'skill', localOperation: 'skill-edit', kind: 'local-operation', safety: 'safe' },
      { id: 'skills-enable', label: 'Enable selected', detail: 'Enable the selected Agent-local skill for later main-conversation guidance.', localKind: 'skill', localOperation: 'skill-enable', kind: 'local-operation', safety: 'safe' },
      { id: 'skills-disable', label: 'Disable selected', detail: 'Disable the selected Agent-local skill without deleting it.', localKind: 'skill', localOperation: 'skill-disable', kind: 'local-operation', safety: 'safe' },
      { id: 'skills-review', label: 'Review selected', detail: 'Mark the selected local skill reviewed after inspecting it.', localKind: 'skill', localOperation: 'skill-review', kind: 'local-operation', safety: 'safe' },
      { id: 'skills-delete', label: 'Delete selected', detail: 'Open a confirmation form before deleting the selected Agent-local skill.', localKind: 'skill', localOperation: 'skill-delete', kind: 'local-operation', safety: 'safe' },
    ],
  },
  {
    id: 'routines',
    group: 'LOCAL BEHAVIOR',
    label: 'Routines',
    summary: 'Repeatable workflows with setup readiness.',
    detail: 'Routines run in the main conversation by default and can declare env/command requirements. Promotion to a connected schedule requires a real schedule command and --yes.',
    actions: [
      { id: 'routines-setup-path', label: 'Routine setup path', detail: 'Create or import a routine, resolve setup gaps, review it, then start it in the main conversation or promote it explicitly to a connected schedule.', kind: 'guidance', safety: 'safe' },
      { id: 'routines-next-action', label: 'Next routine action', detail: 'Use the detail pane to choose the next useful routine step from local readiness, review state, and promotion receipts.', kind: 'guidance', safety: 'safe' },
      { id: 'routines-search', label: 'Search routines', detail: 'Open a search form for Agent-local routines.', editorKind: 'routine-search', kind: 'editor', safety: 'read-only' },
      { id: 'routines-show', label: 'Show routine', detail: 'Open a routine-id form for read-only local routine detail.', editorKind: 'routine-show', kind: 'editor', safety: 'read-only' },
      { id: 'routines-import-discovered', label: 'Import discovered routine', detail: 'Open an in-workspace form that imports one reviewed routine markdown file into the Agent-local routine registry after typed confirmation.', editorKind: 'routine-discovery-import', kind: 'editor', safety: 'safe' },
      { id: 'routines-prev', label: 'Previous routine', detail: 'Move the local routine selection up without changing enabled state.', localKind: 'routine', selectionDelta: -1, kind: 'local-selection', safety: 'safe' },
      { id: 'routines-next', label: 'Next routine', detail: 'Move the local routine selection down without changing enabled state.', localKind: 'routine', selectionDelta: 1, kind: 'local-selection', safety: 'safe' },
      { id: 'routines-create', label: 'Create routine', detail: 'Open an in-workspace form for a repeatable local workflow that writes Agent-local state only.', editorKind: 'routine', kind: 'editor', safety: 'safe' },
      { id: 'routines-edit', label: 'Edit selected', detail: 'Open the selected Agent-local routine in an in-workspace editor.', localKind: 'routine', localOperation: 'routine-edit', kind: 'local-operation', safety: 'safe' },
      { id: 'routines-start', label: 'Start selected', detail: 'Mark the selected routine started and show it as a main-conversation workflow. This creates no hidden job.', localKind: 'routine', localOperation: 'routine-start', kind: 'local-operation', safety: 'safe' },
      { id: 'routines-enable', label: 'Enable selected', detail: 'Enable the selected routine for later main-conversation guidance.', localKind: 'routine', localOperation: 'routine-enable', kind: 'local-operation', safety: 'safe' },
      { id: 'routines-disable', label: 'Disable selected', detail: 'Disable the selected routine without deleting it.', localKind: 'routine', localOperation: 'routine-disable', kind: 'local-operation', safety: 'safe' },
      { id: 'routines-review', label: 'Review selected', detail: 'Mark the selected local routine reviewed after inspecting it.', localKind: 'routine', localOperation: 'routine-review', kind: 'local-operation', safety: 'safe' },
      { id: 'routines-delete', label: 'Delete selected', detail: 'Open a confirmation form before deleting the selected Agent-local routine.', localKind: 'routine', localOperation: 'routine-delete', kind: 'local-operation', safety: 'safe' },
      { id: 'routines-promote', label: 'Promote to schedule', detail: 'Open an in-workspace form that creates one connected schedule from the selected routine with real timing and confirmation.', editorKind: 'routine-schedule', kind: 'editor', safety: 'safe' },
      { id: 'routines-receipt', label: 'Show promotion receipt', detail: 'Open a receipt-id form for read-only routine promotion receipt detail.', editorKind: 'routine-receipt', kind: 'editor', safety: 'read-only' },
    ],
  },
  {
    id: 'work',
    group: 'OPERATIONS',
    label: 'Work & Approvals',
    summary: 'Approvals, background work, host tasks, and delegation.',
    detail: 'Use this workspace to inspect active operator state and approval posture.',
    actions: [
      { id: 'work-autonomy-queue', label: 'Autonomy queue', detail: 'Inspect visible host-task, approval, automation, schedule, routine, and delegation queue cards.', kind: 'guidance', safety: 'read-only' },
      { id: 'work-background-processes', label: 'Background processes', detail: 'Inspect tracked local background processes, bounded output tails, visible monitor routes, and lifecycle controls with execution action:"processes".', kind: 'guidance', safety: 'read-only' },
      { id: 'work-process-capabilities', label: 'Process capabilities', detail: 'Inspect process parity for start/list/poll/wait/log/kill/write, PTY, and sudo before choosing a local execution route.', kind: 'guidance', safety: 'read-only' },
      { id: 'tasks-filter', label: 'Filter host tasks', detail: 'Open a status/kind form for read-only connected-host task filtering.', editorKind: 'task-list-filter', kind: 'editor', safety: 'read-only' },
      { id: 'task-show', label: 'Inspect host task', detail: 'Open a task-id form for read-only connected-host task metadata.', editorKind: 'task-show', kind: 'editor', safety: 'read-only' },
      { id: 'task-output', label: 'Show task output', detail: 'Open a task-id form for read-only connected-host task output.', editorKind: 'task-output', kind: 'editor', safety: 'read-only' },
      { id: 'ci-watches-list', label: 'CI watches', detail: 'List standing CI watches on the connected host. Use /ci status <repo> for a per-job conclusion report, and /ci watches create ... --yes to add a watch with channel delivery.', command: '/ci watches list', kind: 'command', safety: 'read-only' },
      { id: 'approval-review', label: 'Review approval class', detail: 'Open an approval-kind form for read-only review of one approval class.', editorKind: 'approval-review', kind: 'editor', safety: 'read-only' },
      { id: 'approval-approve', label: 'Approve request', detail: 'Open a confirmed form for approving one pending connected-host approval request by id.', editorKind: 'approval-approve', kind: 'editor', safety: 'safe' },
      { id: 'approval-deny', label: 'Deny request', detail: 'Open a confirmed form for denying one pending connected-host approval request by id.', editorKind: 'approval-deny', kind: 'editor', safety: 'safe' },
      { id: 'approval-cancel', label: 'Cancel request', detail: 'Open a confirmed form for cancelling one pending connected-host approval request by id.', editorKind: 'approval-cancel', kind: 'editor', safety: 'safe' },
      { id: 'delegate-task', label: 'Delegate a build task', detail: 'Hand one explicit build, fix, or review task to GoodVibes TUI with the full original ask, reason, and success criteria.', editorKind: 'delegate-task', kind: 'editor', safety: 'delegates' },
      { id: 'work-activity', label: 'Activity', detail: 'Open the Activity view: running work, what needs you, what is coming up, and the recent activity feed (also Ctrl+O).', command: '/activity', kind: 'command', safety: 'read-only' },
    ],
  },
  AGENT_WORKSPACE_HOST_CATEGORY,
  {
    id: 'automation',
    group: 'OPERATIONS',
    label: 'Automation',
    summary: 'Automation limits, reminders, schedules, and routine promotion.',
    detail: 'Agent does not create hidden local automation jobs. Confirmed reminders, reviewed routine promotion, and explicit run/pause/resume controls go through the connected host with confirmation.',
    actions: [
      { id: 'schedule-setup-path', label: 'Schedule setup path', detail: 'Create a reminder or promote a reviewed routine, pick a real cadence, optionally choose a delivery target, confirm, then reconcile receipts with connected schedules.', kind: 'guidance', safety: 'safe' },
      settingAction({ id: 'automation-enabled', label: 'Use automation', detail: 'Toggle the automation subsystem for reminders and scheduled routines.', key: 'automation.enabled' }),
      settingAction({ id: 'automation-max-concurrent', label: 'Concurrent runs', detail: 'Set the maximum automation runs that can execute concurrently.', key: 'automation.maxConcurrentRuns', visibleWhenKey: 'automation.enabled', visibleWhenValue: true }),
      settingAction({ id: 'automation-history-limit', label: 'Run history limit', detail: 'Set the number of run history entries retained per automation job.', key: 'automation.runHistoryLimit', visibleWhenKey: 'automation.enabled', visibleWhenValue: true }),
      settingAction({ id: 'automation-default-timeout', label: 'Default timeout', detail: 'Set the default automation run timeout in milliseconds.', key: 'automation.defaultTimeoutMs', visibleWhenKey: 'automation.enabled', visibleWhenValue: true }),
      settingAction({ id: 'automation-catch-up', label: 'Catch-up window', detail: 'Set how long startup should catch up missed automation runs.', key: 'automation.catchUpWindowMinutes', visibleWhenKey: 'automation.enabled', visibleWhenValue: true }),
      settingAction({ id: 'automation-failure-cooldown', label: 'Failure cooldown', detail: 'Set the cooldown after a failed automation run.', key: 'automation.failureCooldownMs', visibleWhenKey: 'automation.enabled', visibleWhenValue: true }),
      settingAction({ id: 'automation-delete-after-run', label: 'Delete one-shot jobs', detail: 'Toggle deleting one-shot automation jobs after their first successful run.', key: 'automation.deleteAfterRun', visibleWhenKey: 'automation.enabled', visibleWhenValue: true }),
      { id: 'schedule-autonomy-queue', label: 'Autonomy queue', detail: 'Inspect visible reminder, routine promotion, connected schedule, automation run, and cancellation routes.', kind: 'guidance', safety: 'read-only' },
      { id: 'schedule-next-action', label: 'Next schedule action', detail: 'Use the detail pane to choose whether to create a reminder, prepare a routine, promote a routine, or reconcile existing receipts.', kind: 'guidance', safety: 'safe' },
      { id: 'schedule-reminder', label: 'Create reminder', detail: 'Open an in-workspace form that creates one connected reminder schedule with real timing, optional delivery target, and explicit confirmation.', editorKind: 'reminder-schedule', kind: 'editor', safety: 'safe' },
      { id: 'schedule-edit', label: 'Edit schedule', detail: 'Open a confirmed form that edits one connected schedule name, cadence, or prompt by id.', editorKind: 'schedule-edit', kind: 'editor', safety: 'safe' },
      { id: 'automation-job-run', label: 'Run job now', detail: 'Open a confirmed form that runs one connected-host automation job by id.', editorKind: 'automation-job-run', kind: 'editor', safety: 'safe' },
      { id: 'automation-job-pause', label: 'Pause job', detail: 'Open a confirmed form that pauses one connected-host automation job by id.', editorKind: 'automation-job-pause', kind: 'editor', safety: 'safe' },
      { id: 'automation-job-resume', label: 'Resume job', detail: 'Open a confirmed form that resumes one connected-host automation job by id.', editorKind: 'automation-job-resume', kind: 'editor', safety: 'safe' },
      { id: 'automation-run-cancel', label: 'Cancel run', detail: 'Open a confirmed form that cancels one connected-host automation run by id.', editorKind: 'automation-run-cancel', kind: 'editor', safety: 'safe' },
      { id: 'automation-run-retry', label: 'Retry run', detail: 'Open a confirmed form that retries one connected-host automation run by id.', editorKind: 'automation-run-retry', kind: 'editor', safety: 'safe' },
      { id: 'schedule-run', label: 'Run schedule now', detail: 'Open a confirmed form that triggers one connected-host schedule by id.', editorKind: 'schedule-run', kind: 'editor', safety: 'safe' },
      { id: 'schedule-promote-routine', label: 'Promote routine', detail: 'Open an in-workspace form that creates one connected schedule from an Agent-local routine with real timing, optional delivery target, and explicit confirmation.', editorKind: 'routine-schedule', kind: 'editor', safety: 'safe' },
      { id: 'schedule-receipt', label: 'Show receipt', detail: 'Open a receipt-id form for read-only schedule receipt detail.', editorKind: 'schedule-receipt', kind: 'editor', safety: 'read-only' },
      { id: 'schedule-delivery-targets', label: 'Delivery targets', detail: 'Open Channels to pair companion surfaces, inspect route readiness, and add explicit notification targets before reminder delivery.', targetCategoryId: 'onboarding-channels', kind: 'workspace', safety: 'safe' },
      { id: 'schedule-policy', label: 'Local scheduler blocked', detail: 'Local schedule creation remains blocked. Connected edit, run, enable, disable, and delete actions use explicit confirmed forms only.', kind: 'guidance', safety: 'blocked' },
      { id: 'health-repair', label: 'Health repair guidance', detail: 'Open a domain form for read-only health repair guidance.', editorKind: 'health-repair', kind: 'editor', safety: 'read-only' },
    ],
  },
  {
    id: 'finish',
    group: 'FINISH',
    label: 'Finish',
    summary: 'Acknowledge setup and close onboarding.',
    detail: 'Use this final step after reviewing setup. Apply & close writes the user onboarding completion marker so normal future launches start in the main conversation.',
    actions: [{ id: 'onboarding-apply-close', label: 'Apply & close', detail: 'Acknowledge onboarding as finished, persist the user completion marker, and close the fullscreen Agent workspace.', kind: 'onboarding-complete', safety: 'safe' }],
  },
];

export function renderAgentWorkspacePackageText(): string {
  const lines: string[] = [];
  for (const category of AGENT_WORKSPACE_CATEGORIES) {
    lines.push(category.id, category.group, category.label, category.summary, category.detail);
    for (const action of category.actions) {
      lines.push(action.id, action.label, action.detail, action.kind);
      const extras = [
        action.command,
        action.targetCategoryId ? `target:${action.targetCategoryId}` : '',
        action.editorKind ? `editor:${action.editorKind}` : '',
        action.settingKey ? `setting:${action.settingKey}` : '',
        action.modelPickerTarget ? `model-picker-target:${action.modelPickerTarget}` : '',
        action.modelPickerFlow ? `model-picker-flow:${action.modelPickerFlow}` : '',
        action.settingsTarget ? `settings-target:${action.settingsTarget}` : '',
        action.kind === 'settings-import' ? 'import:goodvibes-tui-settings' : '',
        action.setupCheckpointOperation ? `setup-checkpoint:${action.setupCheckpointOperation}` : '',
        action.localKind ? `local:${action.localKind}` : '',
        action.localOperation ? `operation:${action.localOperation}` : '',
      ];
      for (const extra of extras) if (extra) lines.push(extra);
    }
  }
  return lines.join('\n');
}
