/** Separate exact diff material from structurally validated host protocol identities. */
import { snapshotJudgmentInput } from '../../gate/judgment-input.js';
import { captureNativeSelectedDiffContext, type NativeSelectedDiffContext } from './native-diff-context.js';

/** Full identity stays in immutable provenance; semantic readers receive exact quoted material. */
export function nativeSelectedDiffEvidence(value: NativeSelectedDiffContext): { readonly kind: 'session' | 'workspace'; readonly unifiedDiff: string } {
  const captured = captureNativeSelectedDiffContext(value);
  // These encodings are generated by the host, like the canonical UUID/SHA
  // identities inspected by inspectDecisionProtocolReferences. Unknown ID text
  // still crosses the ordinary privacy boundary; no field-name exemption exists.
  const identity = (id: string): string => /^[0-9a-f]{64}$/i.test(id)
    || /^(?:hosted-)?[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(id)
    || /^wcp_[0-9a-z]+_[0-9a-f]{8}$/.test(id) ? '[host-protocol-identity]' : id;
  snapshotJudgmentInput(captured.kind === 'session'
    ? { revision: identity(captured.revision), sessionId: identity(captured.provenance.sessionId),
      baselineCheckpointId: identity(captured.provenance.baselineCheckpointId), latestCheckpointId: identity(captured.provenance.latestCheckpointId) }
    : { revision: identity(captured.revision), baselineId: identity(captured.baselineId) });
  // Diff +/- prefixes must not hide declared credential syntax at line start.
  // Inspect complete body lines too, without altering the evidence we return.
  const lines = captured.unifiedDiff.split('\n');
  const body = lines.slice(lines.findIndex(line => line.startsWith('@@')) + 1);
  snapshotJudgmentInput(body.map(line => /^[ +\-]/.test(line) ? line.slice(1) : line).join('\n'));
  return snapshotJudgmentInput({ kind: captured.kind, unifiedDiff: captured.unifiedDiff }) as { readonly kind: 'session' | 'workspace'; readonly unifiedDiff: string };
}
