import { describe, test, expect } from 'bun:test';
import type { ProjectPlanningState, ProjectPlanningStatus } from '@goodvibes-jev/engine/sdk/platform/knowledge';
import { createPlanningModalSurface, type PlanningModalService } from '../../../views/modals/planning-modal.ts';
import { ConfigModal } from '../../../input/config-modal.ts';
import { actionCtx, tabText } from './modal-surface-test-helpers.ts';

const flush = () => new Promise(resolve => setTimeout(resolve, 0));
const REVISION = Object.freeze({ sourceId: 'saved-source', generation: 'a'.repeat(64) });
const STATUS: ProjectPlanningStatus = { ok: true, projectId: 'proj-1', knowledgeSpaceId: 'project:proj-1', passiveOnly: true, counts: { states: 1, decisions: 0, languageArtifacts: 0, workPlans: 0, workPlanTasks: 0 }, capabilities: [] };
function state(): ProjectPlanningState {
  return { id: 'state-1', projectId: 'proj-1', knowledgeSpaceId: 'project:proj-1', goal: 'Fixture goal', knownContext: [], openQuestions: [], answeredQuestions: [], decisions: [], assumptions: [], constraints: [], risks: [], tasks: [], dependencies: [], verificationGates: [], agentAssignments: [], readiness: 'executable', executionApproved: false, createdAt: 0, updatedAt: 0 };
}
function service(saved: ProjectPlanningState | null): PlanningModalService {
  return {
    status: async () => STATUS,
    getState: async () => ({ ok: true, projectId: 'proj-1', knowledgeSpaceId: 'project:proj-1', state: saved, revision: REVISION }),
    listDecisions: async () => ({ ok: true, projectId: 'proj-1', knowledgeSpaceId: 'project:proj-1', decisions: [] }),
    getLanguage: async () => ({ ok: true, projectId: 'proj-1', knowledgeSpaceId: 'project:proj-1', language: null }),
  };
}
async function open(reads: PlanningModalService) {
  const surface = createPlanningModalSurface({ service: reads, projectId: 'proj-1' });
  surface.onOpen?.(() => {}); await flush(); return surface;
}
function deferred<T>() { let resolve!: (value: T) => void; const promise = new Promise<T>(r => { resolve = r; }); return { promise, resolve }; }

describe('passive historical planning', () => {
  test('keeps modal identity, loading boundary and saved readiness without re-evaluation', async () => {
    const surface = createPlanningModalSurface({ service: service(state()), projectId: 'proj-1' });
    expect(surface.name).toBe('planning-modal'); expect(surface.title).toBe('Historical planning');
    surface.onOpen?.(() => {});
    expect(tabText(surface.buildView(), 'planning')).toContain('Loading historical planning records');
    await flush();
    const text = tabText(surface.buildView(), 'planning');
    expect(text).toContain('saved readiness executable'); expect(text).toContain('historical approval no');
    expect(text).toContain('Historical approval does not grant native execution or migrate records.');
    expect(text).toContain('No saved questions. No new question is generated by this view.');
    expect(text).toContain('saved-source');
    surface.onClose?.();
  });

  for (const hasQuestion of [false, true]) {
    test(`open and refresh ${hasQuestion ? 'saved-question' : 'no-question'} history never evaluate, suggest, mutate or submit`, async () => {
      const saved = { ...state(), readiness: 'needs-user-input' as const, openQuestions: hasQuestion ? [{ id: 'q1', prompt: 'Saved scope question', recommendedAnswer: 'Original advice', status: 'open' as const }] : [] };
      const before = JSON.stringify(saved); const calls: string[] = [];
      const forbidden = async () => { calls.push('forbidden'); throw new Error('No fresh interview'); };
      // Extra runtime methods intentionally simulate the full production service.
      // None is in the view's type-level read-only dependency contract.
      const reads = { ...service(saved), evaluate: forbidden, upsertState: forbidden, applyStateAction: forbidden };
      const deps = { service: reads, projectId: 'proj-1', readAnswerActions: forbidden };
      const surface = createPlanningModalSurface(deps);
      const ctx = actionCtx(null, { executeCommand: async () => { calls.push('command'); return true; }, submitInput: () => calls.push('native'), close: () => calls.push('close'), print: () => calls.push('print') });
      surface.onOpen?.(() => {}); await flush();
      surface.onAction?.('refresh', ctx); await flush();
      for (const id of ['approve', 'submit', 'dismiss', 'answer', 'custom']) surface.onAction?.(id, ctx);
      await flush();
      expect(surface.actions?.map(action => action.id)).toEqual(['refresh']);
      expect(surface.buildView().tabs[0]!.rows.every(row => row.selectable === false)).toBe(true);
      const text = tabText(surface.buildView(), 'planning');
      expect(text).not.toContain('Answer Historical Question'); expect(text).not.toContain('next question:');
      expect(text).not.toContain('Reading answer suggestions');
      if (hasQuestion) { expect(text).toContain('Saved scope question'); expect(text).toContain('saved recommendation: Original advice'); }
      expect(calls).toEqual([]); expect(JSON.stringify(saved)).toBe(before);
      surface.onClose?.();
    });
  }

  test('renders saved questions, answers, decisions, tasks, language and provenance as nonselectable history', async () => {
    const saved: ProjectPlanningState = { ...state(), executionApproved: true, scope: 'Saved scope', knownContext: ['Saved context'], assumptions: ['Saved assumption'], constraints: ['Saved limit'], risks: ['Saved risk'],
      openQuestions: [{ id: 'q', prompt: 'Original question', whyItMatters: 'Original reason', recommendedAnswer: 'Original recommendation', consequence: 'Original consequence', metadata: { artifact: 'question-artifact' } }],
      answeredQuestions: [{ id: 'answered', prompt: 'Old question', answer: 'Saved answer', status: 'answered' }],
      tasks: [{ id: 'task', title: 'Saved task', status: 'completed', dependencies: ['prior'], verification: ['Saved verification'], metadata: { link: 'https://example.com/task' } }],
      decisions: [{ id: 'decision', title: 'Saved choice', decision: 'Use the retained design' }],
      verificationGates: [{ id: 'gate', description: 'Saved gate', status: 'passed' }],
      agentAssignments: [{ taskId: 'task', agentType: 'worker' }],
      metadata: { executionApproved: true, approvedAt: 123, linkedArtifactIds: ['artifact-1'], links: ['https://example.com/saved'] },
    };
    const reads = service(saved);
    const surface = await open({ ...reads, getLanguage: async () => ({ ok: true, projectId: 'proj-1', knowledgeSpaceId: 'project:proj-1', language: { projectId: 'proj-1', knowledgeSpaceId: 'project:proj-1', terms: [{ term: 'Saved term', definition: 'Saved meaning' }], ambiguities: [{ phrase: 'Old phrase', resolution: 'Saved resolution' }], updatedAt: 0 } }) });
    const text = tabText(surface.buildView(), 'planning');
    for (const value of ['Original question', 'Original reason', 'Original consequence', 'Saved answer', 'Saved choice', 'Saved task', 'Saved verification', 'Saved gate', 'Saved meaning', 'Saved resolution', 'artifact-1', 'https://example.com/saved', 'https://example.com/task', 'historical approval yes']) expect(text).toContain(value);
    expect(surface.buildView().tabs[0]!.rows.every(row => row.selectable === false)).toBe(true);
    surface.onClose?.();
  });

  test('missing state and failed reads are explicit and offer only refresh', async () => {
    const empty = await open(service(null));
    expect(tabText(empty.buildView(), 'planning')).toContain('No historical planning state has been saved');
    expect(tabText(empty.buildView(), 'planning')).toContain('/project-plan <goal>');
    empty.onClose?.();
    const failed = await open({ ...service(null), getState: async () => { throw new Error('unavailable'); } });
    expect(tabText(failed.buildView(), 'planning')).toContain('Historical planning records unavailable');
    expect(failed.buildView().hints).toEqual(['r refresh']); failed.onClose?.();
  });

  test('standalone saved decisions and language survive a missing main planning state', async () => {
    const reads = service(null);
    const surface = await open({ ...reads,
      listDecisions: async () => ({ ok: true, projectId: 'proj-1', knowledgeSpaceId: 'project:proj-1', decisions: [{ id: 'separate', title: 'Standalone choice', decision: 'Preserve this saved decision' }] }),
      getLanguage: async () => ({ ok: true, projectId: 'proj-1', knowledgeSpaceId: 'project:proj-1', language: { projectId: 'proj-1', knowledgeSpaceId: 'project:proj-1', terms: [{ term: 'Standalone term', definition: 'Preserve this definition' }], ambiguities: [], updatedAt: 0 } }),
    });
    const text = tabText(surface.buildView(), 'planning');
    expect(text).toContain('No historical planning state has been saved');
    expect(text).toContain('Preserve this saved decision'); expect(text).toContain('Preserve this definition');
    expect(surface.buildView().scrollInformationalLines).toBe(true);
    surface.onClose?.();
  });

  test('completed refresh replaces frozen host rows without another keypress', async () => {
    const old = service({ ...state(), goal: 'Old saved goal' });
    const next = service({ ...state(), goal: 'New saved goal', answeredQuestions: [{ id: 'new', prompt: 'Newly saved question', answer: 'Newly saved answer' }] });
    const gate = deferred<Awaited<ReturnType<PlanningModalService['getState']>>>(); let reads = 0;
    const surface = createPlanningModalSurface({ projectId: 'proj-1', service: { ...old, getState: input => ++reads === 1 ? old.getState(input) : gate.promise } });
    const modal = new ConfigModal(); modal.open(surface); await flush();
    const rendered = () => modal.getRenderModel(100).rows.map(row => row.label).join('\n');
    expect(rendered()).toContain('Old saved goal');
    modal.noteInteraction(); modal.syncStructure();
    expect(modal.fireAction('r', { print: () => {} })).toBe(true);
    expect(rendered()).toContain('Loading historical planning records');
    gate.resolve(await next.getState({ projectId: 'proj-1' })); await flush();
    expect(rendered()).toContain('New saved goal'); expect(rendered()).not.toContain('Old saved goal');
    expect(surface.buildView().tabs[0]!.rows.map(row => row.label).join('\n')).toContain('Newly saved answer');
    modal.close();
  });

  test('delayed reads cannot repaint or resurrect a closed history view', async () => {
    const reads = service(state()); const gate = deferred<Awaited<ReturnType<PlanningModalService['getState']>>>();
    let paints = 0;
    const surface = createPlanningModalSurface({ projectId: 'proj-1', service: { ...reads, getState: () => gate.promise } });
    surface.onOpen?.(() => paints++); surface.onClose?.();
    gate.resolve(await reads.getState({ projectId: 'proj-1' })); await flush();
    expect(paints).toBe(0); expect(tabText(surface.buildView(), 'planning')).not.toContain('Fixture goal');
  });

  test('an older refresh cannot replace a newer snapshot, including close and reopen', async () => {
    const first = deferred<Awaited<ReturnType<PlanningModalService['getState']>>>(); const reads = service(state());
    let calls = 0;
    const surface = createPlanningModalSurface({ projectId: 'proj-1', service: { ...reads, getState: () => ++calls === 1 ? first.promise : service({ ...state(), goal: 'New saved goal' }).getState({ projectId: 'proj-1' }) } });
    surface.onOpen?.(() => {}); surface.onClose?.(); surface.onOpen?.(() => {}); await flush();
    first.resolve(await reads.getState({ projectId: 'proj-1' })); await flush();
    expect(tabText(surface.buildView(), 'planning')).toContain('New saved goal'); expect(tabText(surface.buildView(), 'planning')).not.toContain('Fixture goal');
    surface.onClose?.();
  });
});
