/**
 * Browser, desktop, media, voice, channel, documents, knowledge, security,
 * support, session, release and host-contract routes. Wording is the
 * agent's; variants come from slot readings (slots.ts).
 */
import { quote } from './text.js';
import type { ChannelTask, TaskRouteEntry } from './types.js';

const browserControlPlan: TaskRouteEntry = {
  id: 'browser-control-workflow-plan',
  description: 'Screenshots of the screen, screen recording or observation, or controlling the desktop, mouse and keyboard: computer use beyond one web page.',
  build: (request, slots) => ({
    id: 'browser-control-workflow-plan',
    label: 'Browser, screenshot, or desktop-control workflow plan',
    userSurface: 'Work & Approvals workspace',
    userOutcome: 'Choose the safest browser, screenshot, or desktop-control workflow before any live UI action.',
    why: 'The request asks for screenshot, browser navigation/control, screen observation, or desktop control.',
    modelRoute: `computer action:"plan" query:${quote(request)} includeParameters:true`,
    inspectRoute: 'computer action:"control" includeParameters:true',
    userRoute: 'Agent Workspace -> Work & Approvals',
    requiresConfirmation: slots.starts || slots.changes || slots.opensUi,
    missingFields: ['target page/app/screen when applicable', 'exact live action to perform', 'confirmation for any live-control effect'],
    supportingRoutes: [
      'computer action:"plan" query:"take a screenshot" includeParameters:true',
      'computer action:"mcp" query:"browser desktop" includeParameters:true',
      'computer action:"setup"',
      'computer action:"open_browser" confirm:true explicitUserRequest:"..."',
    ],
    policy: 'Workflow planning is read-only. Browser opens, screenshots, authenticated browsing, form entry, desktop actions, and MCP/tool invocations require the selected tool-specific confirmation boundary.',
  }),
};

const mediaGeneration: TaskRouteEntry = {
  id: 'media-generation-artifact',
  description: 'Generating a new image, video, logo, illustration or other picture with a media model.',
  build: (request) => ({
    id: 'media-generation-artifact',
    label: 'Confirmed media artifact generation',
    userSurface: 'Voice & Media workspace',
    userOutcome: 'Generate image or video only as a confirmed saved artifact with provider readiness visible first.',
    why: 'The request asks to generate, create, render, or draw image/video/media output.',
    modelRoute: 'device action:"provider" target:"media" includeParameters:true',
    inspectRoute: 'agent_harness mode:"media_posture" includeParameters:true',
    userRoute: 'Agent Workspace -> Voice & Media',
    requiresConfirmation: true,
    missingFields: ['media prompt', 'provider/model if the default is not acceptable', 'confirmation'],
    supportingRoutes: [
      `agent_media_generate prompt:${quote(request)} confirm:true explicitUserRequest:${quote(request)}`,
      'agent_artifacts mode:"list" query:"generated media"',
      'agent_knowledge_ingest sourceKind:"artifact" artifactId:"..." confirm:true explicitUserRequest:"..."',
    ],
    policy: 'Media generation requires an explicit user request and confirmation. Generated bytes are saved as artifacts, not printed inline or silently ingested into Knowledge.',
  }),
};

const voiceWorkflow: TaskRouteEntry = {
  id: 'voice-workflow-posture',
  description: 'Talking to the assistant by voice: push-to-talk, wake words, transcribing voice memos or audio, spoken responses.',
  build: (request, slots) => {
    const voiceEffect = slots.starts || slots.changes || slots.opensUi;
    return {
      id: 'voice-workflow-posture',
      label: 'Voice interaction workflow posture',
      userSurface: 'Voice & Media workspace',
      userOutcome: 'Inspect push-to-talk, transcription, spoken-response, and wake-word posture before any voice capture or playback effect.',
      why: 'The request mentions voice workflows, voice memo transcription, push-to-talk, spoken responses, or wake-word capture.',
      modelRoute: `device action:"voice" query:${quote(request)} includeParameters:true`,
      inspectRoute: 'device action:"voice" includeParameters:true',
      userRoute: 'Agent Workspace -> Voice & Media -> Voice readiness',
      requiresConfirmation: voiceEffect,
      missingFields: voiceEffect
        ? ['voice workflow id or audio source', 'selected provider when needed', 'confirmation before capture, transcription, playback, or visible picker handoff']
        : undefined,
      supportingRoutes: [
        'device action:"provider" target:"voice" includeParameters:true',
        'device action:"open_tts_provider" confirm:true explicitUserRequest:"..."',
        'device action:"open_tts_voice" providerId:"..." confirm:true explicitUserRequest:"..."',
        'setup action:"item" setupItemId:"voice-workflows"',
      ],
      policy: 'Voice workflow inspection is read-only. Voice capture, transcription, spoken output, provider picker opens, and wake-word behavior stay unavailable or confirmed until published contracts prove readiness.',
    };
  },
};

const ttsProvider: TaskRouteEntry = {
  id: 'tts-provider-posture',
  description: 'The text-to-speech provider or the synthesized voice the assistant speaks with: choosing, opening the picker for, or changing it.',
  build: (_request, slots) => {
    const openPicker = slots.opensUi || slots.changes;
    return {
      id: 'tts-provider-posture',
      label: 'TTS provider and voice setup posture',
      userSurface: 'Voice & Media workspace',
      userOutcome: 'Inspect TTS provider and voice readiness before opening a picker or changing spoken-response settings.',
      why: 'The request mentions TTS, text-to-speech, speech synthesis, voice provider, or TTS voice selection.',
      modelRoute: 'device action:"provider" target:"tts" includeParameters:true',
      inspectRoute: 'device action:"voice" includeParameters:true',
      userRoute: 'Agent Workspace -> Voice & Media -> TTS provider',
      requiresConfirmation: openPicker,
      missingFields: openPicker ? ['provider or voice target when known', 'confirmation before visible picker handoff or setting change'] : undefined,
      supportingRoutes: [
        'device action:"open_tts_provider" confirm:true explicitUserRequest:"..."',
        'device action:"open_tts_voice" providerId:"..." confirm:true explicitUserRequest:"..."',
        'settings action:"list" query:"tts voice" includeParameters:true',
      ],
      policy: 'TTS inspection is read-only. Opening provider/voice pickers or changing spoken-response settings requires explicit confirmation.',
    };
  },
};

const browserCockpit: TaskRouteEntry = {
  id: 'browser-cockpit-readiness',
  description: "The assistant's own browser cockpit, web dashboard or PWA: opening it or checking that it is ready.",
  build: (_request, slots) => ({
    id: 'browser-cockpit-readiness',
    label: 'Connected browser cockpit/PWA readiness',
    userSurface: 'Connected browser cockpit',
    userOutcome: 'Inspect the configured browser/PWA cockpit and setup routes before opening an external browser.',
    why: 'The request mentions the browser cockpit, PWA, web dashboard, or browser dashboard.',
    modelRoute: 'computer action:"browser" includeParameters:true',
    inspectRoute: 'workspace action:"surface" surfaceId:"connected-browser-cockpit" includeParameters:true',
    userRoute: 'Connected Browser Cockpit (opened through confirmed computer action:"open_browser")',
    requiresConfirmation: slots.opensUi,
    missingFields: slots.opensUi ? ['confirmation before opening the external browser/PWA handoff'] : undefined,
    supportingRoutes: [
      'computer action:"open_browser" confirm:true explicitUserRequest:"..."',
      'workspace action:"open" surfaceId:"connected-browser-cockpit" confirm:true explicitUserRequest:"..."',
      'host action:"services" query:"web" includeParameters:true',
    ],
    policy: 'Browser/PWA readiness is read-only. Opening the connected browser cockpit is a visible confirmed handoff; browser-native Agent workspace routes count as ready only from certified SDK/daemon browser/PWA route and first-run receipt read models.',
  }),
};

const driveABrowser: TaskRouteEntry = {
  id: 'drive-a-browser',
  description: 'Opening a real website or web page and acting on it: browsing, logging in, clicking, filling in forms, scraping or downloading from the site.',
  build: (_request, slots) => ({
    id: 'drive-a-browser',
    label: 'Open and act on a web page',
    userSurface: 'Browser',
    userOutcome: 'Open the page, read what is on it, and act on it.',
    why: 'The request needs a real web page opened, read, or acted on.',
    modelRoute: 'browser action:"navigate" url:"..."',
    inspectRoute: 'browser action:"status"',
    userRoute: 'The browser window the agent opens',
    requiresConfirmation: slots.changes,
    supportingRoutes: [
      'browser action:"snapshot"',
      'browser action:"click" ref:"..."',
      'browser action:"type" ref:"..." text:"..."',
      'browser action:"read_text"',
      'browser action:"launch" headless:false profileName:"..."',
    ],
    policy: 'The browser tool drives a real browser directly and provisions one on first use. Every click and keystroke targets an element from a snapshot of a page it controls. Purchases, sends, and destructive actions need explicit user intent.',
  }),
};

/** Device and voice capability map, or Browser/PWA and computer-use map: the device slot picks the variant. */
const capabilityMap: TaskRouteEntry = {
  id: 'capability-map',
  description: 'Which device, phone, camera, voice, browser, screen or desktop capabilities the assistant has and how they are permissioned.',
  build: (_request, slots) => {
    const device = slots.device;
    return {
      id: device ? 'device-voice-capability' : 'browser-computer-capability',
      label: device ? 'Device and voice capability map' : 'Browser/PWA or computer-use route',
      userSurface: device ? 'Voice & Media workspace' : 'Connected browser cockpit',
      userOutcome: 'Use device, browser, and desktop capabilities only through visible permission-aware routes.',
      why: 'The request mentions browser/PWA, desktop/computer use, mobile, camera, screen, or voice/TTS.',
      modelRoute: device ? 'device action:"status" includeParameters:true' : 'computer action:"status" includeParameters:true',
      inspectRoute: device ? 'device action:"capability" target:"..." includeParameters:true' : 'computer action:"browser" includeParameters:true',
      userRoute: device ? 'Agent Workspace -> Voice & Media' : 'Connected browser cockpit',
      requiresConfirmation: slots.starts || slots.changes || slots.opensUi,
      supportingRoutes: [
        'computer action:"open_browser" confirm:true explicitUserRequest:"..."',
        'device action:"voice"',
        'device action:"open_tts_provider" confirm:true explicitUserRequest:"..."',
      ],
      policy: 'Capability inspection is read-only; browser opens, TTS picker opens, desktop control, and device effects require visible confirmation.',
    };
  },
};

const CHANNEL_VARIANTS: Readonly<Record<ChannelTask, { readonly id: string; readonly label: string; readonly userOutcome: string }>> = {
  receipts: {
    id: 'channel-delivery-receipts',
    label: 'Channel delivery receipts',
    userOutcome: 'Review recent redacted delivery outcomes before retrying or sending more messages.',
  },
  triage: {
    id: 'channel-triage-route',
    label: 'Channel triage and retry posture',
    userOutcome: 'Troubleshoot channel blockers, retries, pending messages, and route bindings without sending.',
  },
  setup: {
    id: 'channel-setup-route',
    label: 'Channel setup guide',
    userOutcome: 'Follow the ordered channel setup guide before relying on external delivery.',
  },
  send: {
    id: 'channel-delivery-boundary',
    label: 'Confirmed channel delivery boundary',
    userOutcome: 'Send and troubleshoot external messages through configured, inspectable channel targets.',
  },
  status: {
    id: 'channel-readiness-route',
    label: 'Channel readiness',
    userOutcome: 'Send and troubleshoot external messages through configured, inspectable channel targets.',
  },
};

/** The five channel routes: the channel-task slot picks the variant, the channel-target selector names the target. */
const channels: TaskRouteEntry = {
  id: 'channels',
  description: 'External messaging channels and notifications (chat apps, push notifications, webhooks): setting one up, sending a message or notification through it, troubleshooting failed deliveries, or reviewing delivery receipts.',
  build: (request, slots) => {
    const target = slots.channelTarget;
    const task = slots.channelTask;
    const variant = CHANNEL_VARIANTS[task];
    const channelRoute = target
      ? `channels action:"channel" target:"${target}" includeParameters:true`
      : `channels action:"status" query:${quote(request)} includeParameters:true`;
    const setupRoute = target
      ? `channels action:"setup" target:"${target}" includeParameters:true`
      : 'channels action:"setup" includeParameters:true';
    const modelRoute = task === 'receipts'
      ? 'channels action:"deliveries" limit:10 includeParameters:true'
      : task === 'triage'
        ? 'channels action:"triage" includeParameters:true'
        : task === 'setup'
          ? setupRoute
          : channelRoute;
    const inspectsStatus = task === 'receipts' || task === 'triage';
    return {
      id: variant.id,
      label: variant.label,
      userSurface: 'Channels workspace',
      userOutcome: variant.userOutcome,
      why: 'The request mentions external channels, notifications, target setup, or delivery receipts.',
      modelRoute,
      inspectRoute: inspectsStatus ? 'channels action:"status" includeParameters:true' : 'channels action:"triage" includeParameters:true',
      userRoute: 'Agent Workspace -> Messaging',
      requiresConfirmation: task === 'setup' || task === 'send',
      missingFields: task === 'send'
        ? ['configured target', 'message text', 'confirmation']
        : task === 'setup'
          ? ['channel/account target', 'configuration or credential route', 'confirmation before mutating channel setup']
          : undefined,
      supportingRoutes: [
        setupRoute,
        'channels action:"triage" includeParameters:true',
        'channels action:"deliveries" limit:10 includeParameters:true',
        'agent_channel_send confirm:true explicitUserRequest:"..."',
        'agent_notify confirm:true explicitUserRequest:"..."',
      ],
      policy: 'Channel inspection is read-only; every external delivery uses an explicit configured target and confirmation.',
    };
  },
};

const documentsArtifacts: TaskRouteEntry = {
  id: 'documents-artifacts-compare',
  description: 'Writing, revising or browsing documents and drafts, uploads, saved artifacts, exports, reviewer packets and handoffs, or running a blind side-by-side comparison of several models\' outputs on a document or task.',
  build: (_request, slots) => ({
    id: 'documents-artifacts-compare',
    label: 'Documents, artifacts, and model comparison',
    userSurface: 'Documents & Files workspace',
    userOutcome: 'Keep drafts, uploads, artifacts, reviewer packets, and model choices in one reviewable workflow.',
    why: 'The request is about documents, artifacts, exports, reviewer packets, or blind model comparison.',
    modelRoute: 'workspace action:"actions" categoryId:"documents" query:"documents compare artifacts"',
    inspectRoute: 'agent_harness mode:"document_ops" includeParameters:true',
    userRoute: 'Agent Workspace -> Documents & Files',
    requiresConfirmation: slots.changes || slots.starts,
    supportingRoutes: [
      'agent_documents action:"browse"',
      'agent_artifacts mode:"list"',
      'agent_model_compare mode:"compare" confirm:true explicitUserRequest:"..."',
      'agent_review_packet_share confirm:true explicitUserRequest:"..."',
    ],
    policy: 'Browsing is read-only; draft changes, exports, archives, sharing, artifact promotion, and comparisons stay confirmed.',
  }),
};

const agentKnowledge: TaskRouteEntry = {
  id: 'agent-knowledge',
  description: "The agent's knowledge base: asking or searching it for source-backed answers, or ingesting new sources into it.",
  build: (_request, slots) => ({
    id: 'agent-knowledge',
    label: 'Isolated Agent Knowledge',
    userSurface: 'Knowledge workspace',
    userOutcome: 'Ask, search, inspect, or deliberately ingest reviewed sources into Agent-owned knowledge only.',
    why: 'The request mentions Agent Knowledge, Knowledge search, source-backed answers, or ingest.',
    modelRoute: 'agent_knowledge action:"ask" query:"..."',
    inspectRoute: 'agent_knowledge action:"status"',
    userRoute: 'Agent Workspace -> Knowledge',
    requiresConfirmation: slots.changes,
    supportingRoutes: [
      'agent_knowledge action:"search" query:"..."',
      'agent_knowledge_ingest sourceKind:"url|file|artifact" confirm:true explicitUserRequest:"..."',
    ],
    policy: 'Agent Knowledge must stay on `/api/goodvibes-agent/knowledge/*` and never fall back to default knowledge.',
  }),
};

const securityStatus: TaskRouteEntry = {
  id: 'security-permission-status',
  description: 'Showing which permissions, approval mode, policies or security settings are currently active.',
  build: (request) => ({
    id: 'security-permission-status',
    label: 'Security and permission posture',
    userSurface: 'Security panel',
    userOutcome: 'Show the current permission, approval, trust, and security posture before changing policy or attempting risky work.',
    why: 'The request asks what permissions, approvals, policies, or safety status are active.',
    modelRoute: `security action:"status" query:${quote(request)} includeParameters:true`,
    inspectRoute: 'security action:"status" includeParameters:true',
    userRoute: '/security',
    requiresConfirmation: false,
    supportingRoutes: [
      'workspace action:"actions" categoryId:"tools-permissions"',
      'settings action:"list" query:"permissions approval policy" includeParameters:true',
      'security action:"finding" findingId:"..." includeParameters:true',
    ],
    policy: 'Security posture inspection is read-only. Permission changes, approval changes, and risky target actions remain separate confirmed routes.',
  }),
};

const securityFinding: TaskRouteEntry = {
  id: 'security-finding-inspection',
  description: 'Inspecting a specific security finding, incident, vulnerability, trust warning or leaked secret or token.',
  build: (request) => ({
    id: 'security-finding-inspection',
    label: 'Security finding inspection',
    userSurface: 'Security panel',
    userOutcome: 'Inspect the exact security finding, trust issue, incident, or leaked-secret record before repair work.',
    why: 'The request asks to inspect a security finding, incident, vulnerability, trust warning, or secret-leak issue.',
    modelRoute: `security action:"finding" target:${quote(request)} includeParameters:true`,
    inspectRoute: 'security action:"status" includeParameters:true',
    userRoute: '/security',
    requiresConfirmation: false,
    supportingRoutes: [
      'security action:"status" includeParameters:true',
      'agent_harness mode:"security_finding" findingId:"..." includeParameters:true',
      'support action:"status" includeParameters:true',
    ],
    policy: 'Finding inspection returns redacted evidence only. Secret rotation, trust changes, MCP enablement, or file edits stay on explicit confirmed repair routes.',
  }),
};

const securityPolicyExplanation: TaskRouteEntry = {
  id: 'security-policy-explanation',
  description: 'Explaining why one tool call or action was or would be allowed, blocked, denied or held for approval or confirmation.',
  build: (_request, slots) => {
    const explainTarget = slots.policyTarget;
    return {
      id: 'security-policy-explanation',
      label: 'Security policy explanation',
      userSurface: 'Security panel',
      userOutcome: 'Explain whether one model action is allowed, blocked, or waiting on confirmation before performing it.',
      why: 'The request asks about a tool, route, command, approval, confirmation, or why an action is allowed, denied, or blocked.',
      modelRoute: explainTarget
        ? `security action:"explain" target:${quote(explainTarget)} toolArgs:{...} includeParameters:true`
        : 'security action:"explain" toolName:"..." toolArgs:{...} includeParameters:true',
      inspectRoute: 'security action:"status" includeParameters:true',
      userRoute: '/security',
      requiresConfirmation: false,
      missingFields: explainTarget ? ['arguments or action details to explain'] : ['tool name or route id', 'arguments or action details to explain'],
      supportingRoutes: [
        'security action:"status" includeParameters:true',
        'security action:"finding" findingId:"..." includeParameters:true',
        'agent_harness mode:"policy_explain" toolName:"..." toolArgs:{...}',
      ],
      policy: 'Policy explanations are read-only and never execute the target tool. Final execution still uses the live route guard, permission prompt, and typed confirmation gate.',
    };
  },
};

const supportBundle: TaskRouteEntry = {
  id: 'support-bundle-route',
  description: 'Support, diagnostic or forensic bundles and support packets: listing, inspecting, exporting, importing or sharing one.',
  build: (request, slots) => ({
    id: 'support-bundle-route',
    label: 'Support bundle and diagnostics packet route',
    userSurface: 'Connected Host workspace',
    userOutcome: 'Inspect available redacted support, diagnostic, trust, auth, or forensic bundles before exporting or importing anything.',
    why: 'The request mentions support bundles, diagnostic bundles, forensic bundles, or support packets.',
    modelRoute: `support action:"status" query:${quote(request)} includeParameters:true`,
    inspectRoute: 'support action:"status" includeParameters:true',
    userRoute: 'Agent Workspace -> Connected Host -> Export support bundle',
    requiresConfirmation: slots.changes,
    missingFields: slots.changes ? ['bundle type or path', 'export/import/share destination when applicable', 'confirmation before bundle export, import, or external sharing'] : undefined,
    supportingRoutes: [
      'support action:"bundle" bundlePath:"..." includeParameters:true',
      'agent_harness mode:"support_bundles" includeParameters:true',
      'workspace action:"actions" query:"support bundle" includeParameters:true',
      'agent_harness mode:"run_workspace_action" actionId:"..." confirm:true explicitUserRequest:"..."',
    ],
    policy: 'Bundle catalog and bundle inspection are read-only and redacted. Bundle export, import, file writes, and sharing remain confirmation-gated workspace or slash-command flows.',
  }),
};

const savedSessions: TaskRouteEntry = {
  id: 'saved-session-route',
  description: 'Saved conversation sessions, bookmarks and transcripts: searching, resuming, loading, renaming, forking, exporting or deleting a past session.',
  build: (request, slots) => {
    const mutation = slots.changes || slots.starts;
    return {
      id: 'saved-session-route',
      label: 'Saved sessions, bookmarks, and transcript continuity',
      userSurface: 'Conversation workspace',
      userOutcome: 'Find, inspect, resume, export, or manage saved Agent sessions and bookmarks from the conversation workspace.',
      why: 'The request mentions saved sessions, session search, transcript export, bookmarks, restore, or conversation continuity.',
      modelRoute: `sessions action:"list" query:${quote(request)} includeParameters:true`,
      inspectRoute: 'sessions action:"list" includeParameters:true',
      userRoute: 'Agent Workspace -> Conversation -> Search saved sessions',
      requiresConfirmation: mutation,
      missingFields: mutation ? ['session id, title, or search target', 'exact lifecycle action', 'confirmation before save/load/resume/rename/fork/export/delete/bookmark changes'] : undefined,
      supportingRoutes: [
        'sessions action:"list" query:"..." includeParameters:true',
        'sessions action:"get" sessionId:"..." includeParameters:true',
        'agent_harness mode:"sessions" includeParameters:true',
        'workspace action:"actions" categoryId:"conversation" query:"session" includeParameters:true',
        'agent_harness mode:"run_workspace_action" actionId:"session-save|session-load|session-export-saved|session-delete" confirm:true explicitUserRequest:"..."',
      ],
      policy: 'Session and bookmark inspection is read-only. Save, load, resume, rename, fork, export, delete, and bookmark writes stay visible and confirmed through workspace or slash-command routes.',
    };
  },
};

/** Release evidence or release readiness: the evidence slot picks the variant. */
const releaseAudit: TaskRouteEntry = {
  id: 'release-audit',
  description: "The product's release audit material: release readiness inventory, release gates, quality dimensions, packaged release evidence, verification ledger or operator audit artifacts.",
  build: (request, slots) => {
    const evidence = slots.evidence;
    return {
      id: evidence ? 'release-evidence-route' : 'release-readiness-route',
      label: evidence ? 'Release evidence artifact route' : 'Release readiness inventory route',
      userSurface: 'Operator/audit release artifacts',
      userOutcome: evidence
        ? 'Inspect packaged release evidence and operator/audit artifacts without expanding raw files blindly.'
        : 'Inspect the release-quality inventory, gates, and readiness dimensions before claiming a product capability is covered.',
      why: 'The request mentions release evidence, readiness inventory, release gates, verification ledger, or operator audit artifacts.',
      modelRoute: evidence
        ? `audit action:"evidence" query:${quote(request)} includeParameters:true`
        : `audit action:"readiness" query:${quote(request)} includeParameters:true`,
      inspectRoute: evidence ? 'audit action:"evidence" includeParameters:true' : 'audit action:"readiness" includeParameters:true',
      userRoute: 'release/ evidence files shipped in the package',
      requiresConfirmation: false,
      supportingRoutes: evidence
        ? [
          'audit action:"artifact" artifactId:"..." includeParameters:true',
          'audit action:"readiness" includeParameters:true',
          'agent_harness mode:"release_evidence" includeParameters:true',
        ]
        : [
          'audit action:"item" itemId:"..." includeParameters:true',
          'audit action:"evidence" includeParameters:true',
          'agent_harness mode:"release_readiness" includeParameters:true',
        ],
      policy: 'Release evidence and readiness inventory inspection are read-only. They expose packaged audit facts and bounded artifact content, not product mutations.',
    };
  },
};

const connectedHostContract: TaskRouteEntry = {
  id: 'connected-host-contract',
  description: 'Which methods, API routes, service endpoints or capabilities the daemon or control plane publishes as its contract.',
  build: () => ({
    id: 'connected-host-contract',
    label: 'Connected host capability or method contract',
    userSurface: 'Connected host diagnostics',
    userOutcome: 'Inspect daemon capabilities through public contracts instead of guessing hidden routes.',
    why: 'The request asks about daemon/operator/API route capability or service posture.',
    modelRoute: 'host action:"capabilities" includeParameters:true',
    inspectRoute: 'host action:"methods" includeParameters:true',
    userRoute: 'Agent Workspace -> Start',
    requiresConfirmation: false,
    supportingRoutes: [
      'host action:"method" methodId:"..."',
      'agent_operator_method methodId:"..." confirm:true explicitUserRequest:"..."',
      'host action:"services" includeParameters:true',
    ],
    policy: 'Method discovery is read-only; write/admin daemon methods require exact method id, confirmation, and an explicit user request.',
  }),
};

export const SURFACE_ROUTES: readonly TaskRouteEntry[] = [
  browserControlPlan,
  mediaGeneration,
  voiceWorkflow,
  ttsProvider,
  browserCockpit,
  driveABrowser,
  capabilityMap,
  channels,
  documentsArtifacts,
  agentKnowledge,
  securityStatus,
  securityFinding,
  securityPolicyExplanation,
  supportBundle,
  savedSessions,
  releaseAudit,
  connectedHostContract,
];
