/**
 * Session auto-titler.
 *
 * When `session.autoTitle` is enabled, an untitled session is given a short
 * title generated by the configured tool/helper (weak/fast) model after the
 * first turn completes. It is OFF by default because it spends a small model
 * call. It only ever sets a SYSTEM-sourced title, so a user-chosen title is
 * never overwritten, and it runs at most once per session.
 */

import type { ConversationMessageSnapshot } from '@goodvibes-jev/engine/sdk/platform/core';
import type { ConfigManager } from '@goodvibes-jev/engine/sdk/platform/config';
import { createSessionTitleGenerator, type SessionTitleModel } from '@goodvibes-jev/engine/sdk/platform/sessions';
export { sanitizeSessionTitle as sanitizeTitle } from '@goodvibes-jev/engine/sdk/platform/sessions';
import { readSessionSettings } from '../config/tui-extension-settings.ts';

/** Minimal conversation surface the titler needs. */
export interface TitlerConversation {
  readonly title: string;
  /** Changes only when the conversation is replaced, never on append. */
  getReplacementGeneration(): number;
  getTitleSource(): 'system' | 'user';
  setSystemTitle(value: string): void;
  getMessageSnapshot(): ConversationMessageSnapshot[];
}

/** Configured helper-model contract owned by the engine. */
export type TitlerModel = SessionTitleModel;

export interface SessionAutoTitlerOptions {
  readonly conversation: TitlerConversation;
  readonly model: TitlerModel;
  readonly configManager: Pick<ConfigManager, 'getRaw'>;
  readonly turns: { on(event: string, handler: () => void): () => void };
  /** Called with the generated title after it is applied (for a system message / repaint). */
  readonly onTitled?: (title: string) => void;
  readonly getSessionId?: () => string;
  readonly isActive?: () => boolean;
  /** Test seams. */
  readonly readSettings?: (configManager: Pick<ConfigManager, 'getRaw'>) => { autoTitle?: boolean };
}

export interface SessionAutoTitler {
  readonly unsubs: ReadonlyArray<() => void>;
  /** Attempt titling now (used by the turn handler; exposed for testing). */
  maybeTitle(): Promise<void>;
}

/** The TUI owns settings, events, session identity and applying the shared result. */
export function createSessionAutoTitler(options: SessionAutoTitlerOptions): SessionAutoTitler {
  const readSettings = options.readSettings ?? readSessionSettings;
  const generator = createSessionTitleGenerator(options.model);
  let closed = false;

  const maybeTitle = async (): Promise<void> => {
    if (closed || options.isActive?.() === false) return;
    if (!readSettings(options.configManager).autoTitle) return;
    if (options.conversation.getTitleSource() === 'user') return;
    const sessionId = options.getSessionId?.();
    const generation = options.conversation.getReplacementGeneration();
    try {
      const title = await generator.generate(() => options.conversation.getMessageSnapshot());
      if (!title || closed || options.isActive?.() === false) return;
      if (sessionId !== options.getSessionId?.() || generation !== options.conversation.getReplacementGeneration()) return;
      // Re-check immediately before application: the user may have named it.
      if (options.conversation.getTitleSource() === 'user') return;
      options.conversation.setSystemTitle(title);
      options.onTitled?.(title);
    } catch {
      // Preserve the optional feature's silent, best-effort delivery contract.
    }
  };

  const off = options.turns.on('TURN_COMPLETED', () => { void maybeTitle(); });
  const unsubs = [() => { closed = true; off(); }];
  return { unsubs, maybeTitle };
}
